//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.SpRuntime
{
    
    
    /// <summary>
    /// >> Path: sp_runtime.generic.header.Header
    /// </summary>
    public sealed class Header : BaseType
    {
        
        private SubstrateNetApi.Model.PrimitiveTypes.H256 _parentHash;
        
        private BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> _number;
        
        private SubstrateNetApi.Model.PrimitiveTypes.H256 _stateRoot;
        
        private SubstrateNetApi.Model.PrimitiveTypes.H256 _extrinsicsRoot;
        
        private SubstrateNetApi.Model.SpRuntime.Digest _digest;
        
        public SubstrateNetApi.Model.PrimitiveTypes.H256 ParentHash
        {
            get
            {
                return this._parentHash;
            }
            set
            {
                this._parentHash = value;
            }
        }
        
        public BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> Number
        {
            get
            {
                return this._number;
            }
            set
            {
                this._number = value;
            }
        }
        
        public SubstrateNetApi.Model.PrimitiveTypes.H256 StateRoot
        {
            get
            {
                return this._stateRoot;
            }
            set
            {
                this._stateRoot = value;
            }
        }
        
        public SubstrateNetApi.Model.PrimitiveTypes.H256 ExtrinsicsRoot
        {
            get
            {
                return this._extrinsicsRoot;
            }
            set
            {
                this._extrinsicsRoot = value;
            }
        }
        
        public SubstrateNetApi.Model.SpRuntime.Digest Digest
        {
            get
            {
                return this._digest;
            }
            set
            {
                this._digest = value;
            }
        }
        
        public override string TypeName()
        {
            return "Header";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(ParentHash.Encode());
            result.AddRange(Number.Encode());
            result.AddRange(StateRoot.Encode());
            result.AddRange(ExtrinsicsRoot.Encode());
            result.AddRange(Digest.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            ParentHash = new SubstrateNetApi.Model.PrimitiveTypes.H256();
            ParentHash.Decode(byteArray, ref p);
            Number = new BaseCom<SubstrateNetApi.Model.Types.Primitive.U32>();
            Number.Decode(byteArray, ref p);
            StateRoot = new SubstrateNetApi.Model.PrimitiveTypes.H256();
            StateRoot.Decode(byteArray, ref p);
            ExtrinsicsRoot = new SubstrateNetApi.Model.PrimitiveTypes.H256();
            ExtrinsicsRoot.Decode(byteArray, ref p);
            Digest = new SubstrateNetApi.Model.SpRuntime.Digest();
            Digest.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
