//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.SpConsensusBabe
{
    
    
    public enum NextConfigDescriptor
    {
        
        V1,
    }
    
    /// <summary>
    /// >> Enum
    /// </summary>
    public sealed class EnumNextConfigDescriptor : BaseEnumExt<NextConfigDescriptor, BaseTuple<BaseTuple<SubstrateNetApi.Model.Types.Primitive.U64,SubstrateNetApi.Model.Types.Primitive.U64>, SubstrateNetApi.Model.SpConsensusBabe.EnumAllowedSlots>>
    {
    }
}
