//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.SpCore
{
    
    
    /// <summary>
    /// >> Path: sp_core.changes_trie.ChangesTrieConfiguration
    /// </summary>
    public sealed class ChangesTrieConfiguration : BaseType
    {
        
        private SubstrateNetApi.Model.Types.Primitive.U32 _digestInterval;
        
        private SubstrateNetApi.Model.Types.Primitive.U32 _digestLevels;
        
        public SubstrateNetApi.Model.Types.Primitive.U32 DigestInterval
        {
            get
            {
                return this._digestInterval;
            }
            set
            {
                this._digestInterval = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U32 DigestLevels
        {
            get
            {
                return this._digestLevels;
            }
            set
            {
                this._digestLevels = value;
            }
        }
        
        public override string TypeName()
        {
            return "ChangesTrieConfiguration";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(DigestInterval.Encode());
            result.AddRange(DigestLevels.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            DigestInterval = new SubstrateNetApi.Model.Types.Primitive.U32();
            DigestInterval.Decode(byteArray, ref p);
            DigestLevels = new SubstrateNetApi.Model.Types.Primitive.U32();
            DigestLevels.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
