//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Base;
using SubstrateNetApi.Model.Extrinsics;
using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.PrimitiveTypes;
using SubstrateNetApi.Model.SpStaking;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletOffences
{
    
    
    public sealed class OffencesStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public OffencesStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        public static string ReportsParams(SubstrateNetApi.Model.PrimitiveTypes.H256 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Offences", "Reports", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Reports
        /// </summary>
        public async Task<SubstrateNetApi.Model.SpStaking.OffenceDetails> Reports(SubstrateNetApi.Model.PrimitiveTypes.H256 key, CancellationToken token)
        {
            string parameters = OffencesStorage.ReportsParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.SpStaking.OffenceDetails>(parameters, token);
        }
        
        public static string ConcurrentReportsIndexParams(BaseTuple<SubstrateNetApi.Model.Base.Arr16U8,BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>> key)
        {
            var keyParams = key.Value;
            var parameters = RequestGenerator.GetStorage("Offences", "ConcurrentReportsIndex", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat,Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ConcurrentReportsIndex
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.PrimitiveTypes.H256>> ConcurrentReportsIndex(BaseTuple<SubstrateNetApi.Model.Base.Arr16U8,BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>> key, CancellationToken token)
        {
            string parameters = OffencesStorage.ConcurrentReportsIndexParams(key);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.PrimitiveTypes.H256>>(parameters, token);
        }
        
        public static string ReportsByKindIndexParams(SubstrateNetApi.Model.Base.Arr16U8 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Offences", "ReportsByKindIndex", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ReportsByKindIndex
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>> ReportsByKindIndex(SubstrateNetApi.Model.Base.Arr16U8 key, CancellationToken token)
        {
            string parameters = OffencesStorage.ReportsByKindIndexParams(key);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>>(parameters, token);
        }
    }
    
    public sealed class OffencesCalls
    {
    }
    
    /// <summary>
    /// >> Offence
    /// </summary>
    public sealed class EventOffence : BaseTuple<SubstrateNetApi.Model.Base.Arr16U8, BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>>
    {
    }
}
