//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.PalletElectionsPhragmen;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.SpRuntime;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletElections
{
    
    
    public sealed class ElectionsStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public ElectionsStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        /// <summary>
        /// >> Members
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>> Members(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "Members", Storage.Type.Plain);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>>(parameters, token);
        }
        
        /// <summary>
        /// >> RunnersUp
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>> RunnersUp(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "RunnersUp", Storage.Type.Plain);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>>(parameters, token);
        }
        
        /// <summary>
        /// >> Candidates
        /// </summary>
        public async Task<BaseVec<BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U128>>> Candidates(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "Candidates", Storage.Type.Plain);
            return await _client.GetStorageAsync<BaseVec<BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U128>>>(parameters, token);
        }
        
        /// <summary>
        /// >> ElectionRounds
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> ElectionRounds(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "ElectionRounds", Storage.Type.Plain);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        /// <summary>
        /// >> Voting
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletElectionsPhragmen.Voter> Voting(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Elections", "Voting", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletElectionsPhragmen.Voter>(parameters, token);
        }
    }
    
    public sealed class ElectionsCalls
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public ElectionsCalls(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        /// <summary>
        /// >> vote
        /// </summary>
        public GenericExtrinsicCall Vote(BaseVec<SubstrateNetApi.Model.SpCore.AccountId32> votes, BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> value)
        {
            return new GenericExtrinsicCall(14, "Elections", 0, "vote", votes, value);
        }
        
        /// <summary>
        /// >> remove_voter
        /// </summary>
        public GenericExtrinsicCall RemoveVoter()
        {
            return new GenericExtrinsicCall(14, "Elections", 1, "remove_voter");
        }
        
        /// <summary>
        /// >> submit_candidacy
        /// </summary>
        public GenericExtrinsicCall SubmitCandidacy(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> candidate_count)
        {
            return new GenericExtrinsicCall(14, "Elections", 2, "submit_candidacy", candidate_count);
        }
        
        /// <summary>
        /// >> renounce_candidacy
        /// </summary>
        public GenericExtrinsicCall RenounceCandidacy(SubstrateNetApi.Model.PalletElectionsPhragmen.EnumRenouncing renouncing)
        {
            return new GenericExtrinsicCall(14, "Elections", 3, "renounce_candidacy", renouncing);
        }
        
        /// <summary>
        /// >> remove_member
        /// </summary>
        public GenericExtrinsicCall RemoveMember(SubstrateNetApi.Model.SpRuntime.EnumMultiAddress who, SubstrateNetApi.Model.Types.Primitive.Bool has_replacement)
        {
            return new GenericExtrinsicCall(14, "Elections", 4, "remove_member", who, has_replacement);
        }
        
        /// <summary>
        /// >> clean_defunct_voters
        /// </summary>
        public GenericExtrinsicCall CleanDefunctVoters(SubstrateNetApi.Model.Types.Primitive.U32 num_voters, SubstrateNetApi.Model.Types.Primitive.U32 num_defunct)
        {
            return new GenericExtrinsicCall(14, "Elections", 5, "clean_defunct_voters", num_voters, num_defunct);
        }
    }
    
    /// <summary>
    /// >> NewTerm
    /// </summary>
    public sealed class EventNewTerm : BaseTuple<BaseVec<BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U128>>>
    {
    }
    
    /// <summary>
    /// >> EmptyTerm
    /// </summary>
    public sealed class EventEmptyTerm : BaseTuple
    {
    }
    
    /// <summary>
    /// >> ElectionError
    /// </summary>
    public sealed class EventElectionError : BaseTuple
    {
    }
    
    /// <summary>
    /// >> MemberKicked
    /// </summary>
    public sealed class EventMemberKicked : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> Renounced
    /// </summary>
    public sealed class EventRenounced : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> CandidateSlashed
    /// </summary>
    public sealed class EventCandidateSlashed : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> SeatHolderSlashed
    /// </summary>
    public sealed class EventSeatHolderSlashed : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    public enum ElectionsErrors
    {
        
        /// <summary>
        /// >> UnableToVote
        /// </summary>
        UnableToVote,
        
        /// <summary>
        /// >> NoVotes
        /// </summary>
        NoVotes,
        
        /// <summary>
        /// >> TooManyVotes
        /// </summary>
        TooManyVotes,
        
        /// <summary>
        /// >> MaximumVotesExceeded
        /// </summary>
        MaximumVotesExceeded,
        
        /// <summary>
        /// >> LowBalance
        /// </summary>
        LowBalance,
        
        /// <summary>
        /// >> UnableToPayBond
        /// </summary>
        UnableToPayBond,
        
        /// <summary>
        /// >> MustBeVoter
        /// </summary>
        MustBeVoter,
        
        /// <summary>
        /// >> ReportSelf
        /// </summary>
        ReportSelf,
        
        /// <summary>
        /// >> DuplicatedCandidate
        /// </summary>
        DuplicatedCandidate,
        
        /// <summary>
        /// >> MemberSubmit
        /// </summary>
        MemberSubmit,
        
        /// <summary>
        /// >> RunnerUpSubmit
        /// </summary>
        RunnerUpSubmit,
        
        /// <summary>
        /// >> InsufficientCandidateFunds
        /// </summary>
        InsufficientCandidateFunds,
        
        /// <summary>
        /// >> NotMember
        /// </summary>
        NotMember,
        
        /// <summary>
        /// >> InvalidWitnessData
        /// </summary>
        InvalidWitnessData,
        
        /// <summary>
        /// >> InvalidVoteCount
        /// </summary>
        InvalidVoteCount,
        
        /// <summary>
        /// >> InvalidRenouncing
        /// </summary>
        InvalidRenouncing,
        
        /// <summary>
        /// >> InvalidReplacement
        /// </summary>
        InvalidReplacement,
    }
}
