//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.PalletElectionsPhragmen;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletElections
{
    
    
    public sealed class PalletElectionsStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public PalletElectionsStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        /// <summary>
        /// >> Members
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>> Members(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "Members", Storage.Type.Plain);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>>(parameters, token);
        }
        
        /// <summary>
        /// >> RunnersUp
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>> RunnersUp(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "RunnersUp", Storage.Type.Plain);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.PalletElectionsPhragmen.SeatHolder>>(parameters, token);
        }
        
        /// <summary>
        /// >> Candidates
        /// </summary>
        public async Task<BaseVec<BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U128>>> Candidates(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "Candidates", Storage.Type.Plain);
            return await _client.GetStorageAsync<BaseVec<BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U128>>>(parameters, token);
        }
        
        /// <summary>
        /// >> ElectionRounds
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> ElectionRounds(CancellationToken token)
        {
            var parameters = RequestGenerator.GetStorage("Elections", "ElectionRounds", Storage.Type.Plain);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        /// <summary>
        /// >> Voting
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletElectionsPhragmen.Voter> Voting(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Elections", "Voting", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletElectionsPhragmen.Voter>(parameters, token);
        }
    }
}
