//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.PalletImOnline;
using SubstrateNetApi.Model.PalletStaking;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletImOnline
{
    
    
    /// <summary>
    /// >> 57 - Variant[pallet_im_online.pallet.Event]
    /// 
    ///			The [event](https://substrate.dev/docs/en/knowledgebase/runtime/events) emitted
    ///			by this pallet.
    ///			
    /// </summary>
    public sealed class PalletImOnlineEvent
    {
        
        /// <summary>
        /// >> HeartbeatReceived
        /// </summary>
        public sealed class HeartbeatReceived : BaseTuple<SubstrateNetApi.Model.PalletImOnline.Public>
        {
        }
        
        /// <summary>
        /// >> AllGood
        /// </summary>
        public sealed class AllGood : BaseTuple
        {
        }
        
        /// <summary>
        /// >> SomeOffline
        /// </summary>
        public sealed class SomeOffline : BaseTuple<BaseVec<BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.PalletStaking.Exposure>>>
        {
        }
    }
}
