//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Extrinsics;
using SubstrateNetApi.Model.FrameSupport;
using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.NodeRuntime;
using SubstrateNetApi.Model.PalletCollective;
using SubstrateNetApi.Model.PrimitiveTypes;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletTechnicalCommittee
{
    
    
    public sealed class TechnicalCommitteeStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public TechnicalCommitteeStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        public static string ProposalsParams()
        {
            var parameters = RequestGenerator.GetStorage("TechnicalCommittee", "Proposals", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> Proposals
        /// </summary>
        public async Task<SubstrateNetApi.Model.FrameSupport.BoundedVec> Proposals(CancellationToken token)
        {
            string parameters = TechnicalCommitteeStorage.ProposalsParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.FrameSupport.BoundedVec>(parameters, token);
        }
        
        public static string ProposalOfParams(SubstrateNetApi.Model.PrimitiveTypes.H256 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("TechnicalCommittee", "ProposalOf", Storage.Type.Map, new[] {Storage.Hasher.Identity}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ProposalOf
        /// </summary>
        public async Task<SubstrateNetApi.Model.NodeRuntime.EnumNodeCall> ProposalOf(SubstrateNetApi.Model.PrimitiveTypes.H256 key, CancellationToken token)
        {
            string parameters = TechnicalCommitteeStorage.ProposalOfParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.NodeRuntime.EnumNodeCall>(parameters, token);
        }
        
        public static string VotingParams(SubstrateNetApi.Model.PrimitiveTypes.H256 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("TechnicalCommittee", "Voting", Storage.Type.Map, new[] {Storage.Hasher.Identity}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Voting
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletCollective.Votes> Voting(SubstrateNetApi.Model.PrimitiveTypes.H256 key, CancellationToken token)
        {
            string parameters = TechnicalCommitteeStorage.VotingParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletCollective.Votes>(parameters, token);
        }
        
        public static string ProposalCountParams()
        {
            var parameters = RequestGenerator.GetStorage("TechnicalCommittee", "ProposalCount", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> ProposalCount
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> ProposalCount(CancellationToken token)
        {
            string parameters = TechnicalCommitteeStorage.ProposalCountParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string MembersParams()
        {
            var parameters = RequestGenerator.GetStorage("TechnicalCommittee", "Members", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> Members
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.SpCore.AccountId32>> Members(CancellationToken token)
        {
            string parameters = TechnicalCommitteeStorage.MembersParams();
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.SpCore.AccountId32>>(parameters, token);
        }
        
        public static string PrimeParams()
        {
            var parameters = RequestGenerator.GetStorage("TechnicalCommittee", "Prime", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> Prime
        /// </summary>
        public async Task<SubstrateNetApi.Model.SpCore.AccountId32> Prime(CancellationToken token)
        {
            string parameters = TechnicalCommitteeStorage.PrimeParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.SpCore.AccountId32>(parameters, token);
        }
    }
    
    public sealed class TechnicalCommitteeCalls
    {
        
        /// <summary>
        /// >> set_members
        /// </summary>
        public static Method SetMembers(BaseVec<SubstrateNetApi.Model.SpCore.AccountId32> new_members, BaseOpt<SubstrateNetApi.Model.SpCore.AccountId32> prime, SubstrateNetApi.Model.Types.Primitive.U32 old_count)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(new_members.Encode());
            byteArray.AddRange(prime.Encode());
            byteArray.AddRange(old_count.Encode());
            return new Method(13, "TechnicalCommittee", 0, "set_members", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> execute
        /// </summary>
        public static Method Execute(SubstrateNetApi.Model.NodeRuntime.EnumNodeCall proposal, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> length_bound)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(proposal.Encode());
            byteArray.AddRange(length_bound.Encode());
            return new Method(13, "TechnicalCommittee", 1, "execute", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> propose
        /// </summary>
        public static Method Propose(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> threshold, SubstrateNetApi.Model.NodeRuntime.EnumNodeCall proposal, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> length_bound)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(threshold.Encode());
            byteArray.AddRange(proposal.Encode());
            byteArray.AddRange(length_bound.Encode());
            return new Method(13, "TechnicalCommittee", 2, "propose", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> vote
        /// </summary>
        public static Method Vote(SubstrateNetApi.Model.PrimitiveTypes.H256 proposal, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> index, SubstrateNetApi.Model.Types.Primitive.Bool approve)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(proposal.Encode());
            byteArray.AddRange(index.Encode());
            byteArray.AddRange(approve.Encode());
            return new Method(13, "TechnicalCommittee", 3, "vote", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> close
        /// </summary>
        public static Method Close(SubstrateNetApi.Model.PrimitiveTypes.H256 proposal_hash, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> index, BaseCom<SubstrateNetApi.Model.Types.Primitive.U64> proposal_weight_bound, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> length_bound)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(proposal_hash.Encode());
            byteArray.AddRange(index.Encode());
            byteArray.AddRange(proposal_weight_bound.Encode());
            byteArray.AddRange(length_bound.Encode());
            return new Method(13, "TechnicalCommittee", 4, "close", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> disapprove_proposal
        /// </summary>
        public static Method DisapproveProposal(SubstrateNetApi.Model.PrimitiveTypes.H256 proposal_hash)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(proposal_hash.Encode());
            return new Method(13, "TechnicalCommittee", 5, "disapprove_proposal", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> Proposed
    /// </summary>
    public sealed class EventProposed : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.PrimitiveTypes.H256, SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> Voted
    /// </summary>
    public sealed class EventVoted : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.PrimitiveTypes.H256, SubstrateNetApi.Model.Types.Primitive.Bool, SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> Approved
    /// </summary>
    public sealed class EventApproved : BaseTuple<SubstrateNetApi.Model.PrimitiveTypes.H256>
    {
    }
    
    /// <summary>
    /// >> Disapproved
    /// </summary>
    public sealed class EventDisapproved : BaseTuple<SubstrateNetApi.Model.PrimitiveTypes.H256>
    {
    }
    
    /// <summary>
    /// >> Executed
    /// </summary>
    public sealed class EventExecuted : BaseTuple<SubstrateNetApi.Model.PrimitiveTypes.H256, BaseTuple<BaseTuple,  SubstrateNetApi.Model.SpRuntime.EnumDispatchError>>
    {
    }
    
    /// <summary>
    /// >> MemberExecuted
    /// </summary>
    public sealed class EventMemberExecuted : BaseTuple<SubstrateNetApi.Model.PrimitiveTypes.H256, BaseTuple<BaseTuple,  SubstrateNetApi.Model.SpRuntime.EnumDispatchError>>
    {
    }
    
    /// <summary>
    /// >> Closed
    /// </summary>
    public sealed class EventClosed : BaseTuple<SubstrateNetApi.Model.PrimitiveTypes.H256, SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    public enum TechnicalCommitteeErrors
    {
        
        /// <summary>
        /// >> NotMember
        /// </summary>
        NotMember,
        
        /// <summary>
        /// >> DuplicateProposal
        /// </summary>
        DuplicateProposal,
        
        /// <summary>
        /// >> ProposalMissing
        /// </summary>
        ProposalMissing,
        
        /// <summary>
        /// >> WrongIndex
        /// </summary>
        WrongIndex,
        
        /// <summary>
        /// >> DuplicateVote
        /// </summary>
        DuplicateVote,
        
        /// <summary>
        /// >> AlreadyInitialized
        /// </summary>
        AlreadyInitialized,
        
        /// <summary>
        /// >> TooEarly
        /// </summary>
        TooEarly,
        
        /// <summary>
        /// >> TooManyProposals
        /// </summary>
        TooManyProposals,
        
        /// <summary>
        /// >> WrongProposalWeight
        /// </summary>
        WrongProposalWeight,
        
        /// <summary>
        /// >> WrongProposalLength
        /// </summary>
        WrongProposalLength,
    }
}
