//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.FrameSystem
{
    
    
    /// <summary>
    /// >> Path: frame_system.pallet.Event
    /// Event for the System pallet.
    /// </summary>
    public sealed class FrameSystemEvent
    {
        
        /// <summary>
        /// >> Event: ExtrinsicSuccess
        /// An extrinsic completed successfully. \[info\]
        /// </summary>
        public sealed class ExtrinsicSuccess : BaseTuple<SubstrateNetApi.Model.FrameSupport.DispatchInfo>
        {
        }
        
        /// <summary>
        /// >> Event: ExtrinsicFailed
        /// An extrinsic failed. \[error, info\]
        /// </summary>
        public sealed class ExtrinsicFailed : BaseTuple<SubstrateNetApi.Model.SpRuntime.EnumDispatchError, SubstrateNetApi.Model.FrameSupport.DispatchInfo>
        {
        }
        
        /// <summary>
        /// >> Event: CodeUpdated
        /// `:code` was updated.
        /// </summary>
        public sealed class CodeUpdated : BaseTuple
        {
        }
        
        /// <summary>
        /// >> Event: NewAccount
        /// A new \[account\] was created.
        /// </summary>
        public sealed class NewAccount : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: KilledAccount
        /// An \[account\] was reaped.
        /// </summary>
        public sealed class KilledAccount : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: Remarked
        /// On on-chain remark happened. \[origin, remark_hash\]
        /// </summary>
        public sealed class Remarked : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.PrimitiveTypes.H256>
        {
        }
    }
}
