//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Calls;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Composite;
using SubstrateNetApi.Model.Types.Enum;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.Sequence;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Custom.Calls
{
    
    
    /// <summary>
    /// >> Path: pallet_identity.pallet.Call
    /// Identity pallet declaration.
    /// </summary>
    public sealed class PalletIdentity
    {
        
        /// <summary>
        /// >> Extrinsic: add_registrar
        /// Add a registrar to the system.
        /// 
        /// The dispatch origin for this call must be `T::RegistrarOrigin`.
        /// 
        /// - `account`: the account of the registrar.
        /// 
        /// Emits `RegistrarAdded` if successful.
        /// 
        /// # <weight>
        /// - `O(R)` where `R` registrar-count (governance-bounded and code-bounded).
        /// - One storage mutation (codec `O(R)`).
        /// - One event.
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall AddRegistrar(AccountId32 account)
        {
            return new GenericExtrinsicCall("Identity", "add_registrar", account);
        }
        
        /// <summary>
        /// >> Extrinsic: set_identity
        /// Set an account's identity information and reserve the appropriate deposit.
        /// 
        /// If the account already has identity information, the deposit is taken as part payment
        /// for the new deposit.
        /// 
        /// The dispatch origin for this call must be _Signed_.
        /// 
        /// - `info`: The identity information.
        /// 
        /// Emits `IdentitySet` if successful.
        /// 
        /// # <weight>
        /// - `O(X + X' + R)`
        ///   - where `X` additional-field-count (deposit-bounded and code-bounded)
        ///   - where `R` judgements-count (registrar-count-bounded)
        /// - One balance reserve operation.
        /// - One storage mutation (codec-read `O(X' + R)`, codec-write `O(X + R)`).
        /// - One event.
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall SetIdentity(IdentityInfo info)
        {
            return new GenericExtrinsicCall("Identity", "set_identity", info);
        }
        
        /// <summary>
        /// >> Extrinsic: set_subs
        /// Set the sub-accounts of the sender.
        /// 
        /// Payment: Any aggregate balance reserved by previous `set_subs` calls will be returned
        /// and an amount `SubAccountDeposit` will be reserved for each item in `subs`.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a registered
        /// identity.
        /// 
        /// - `subs`: The identity's (new) sub-accounts.
        /// 
        /// # <weight>
        /// - `O(P + S)`
        ///   - where `P` old-subs-count (hard- and deposit-bounded).
        ///   - where `S` subs-count (hard- and deposit-bounded).
        /// - At most one balance operations.
        /// - DB:
        ///   - `P + S` storage mutations (codec complexity `O(1)`)
        ///   - One storage read (codec complexity `O(P)`).
        ///   - One storage write (codec complexity `O(S)`).
        ///   - One storage-exists (`IdentityOf::contains_key`).
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall SetSubs(BaseVec<BaseTuple<AccountId32,EnumData>> subs)
        {
            return new GenericExtrinsicCall("Identity", "set_subs", subs);
        }
        
        /// <summary>
        /// >> Extrinsic: clear_identity
        /// Clear an account's identity info and all sub-accounts and return all deposits.
        /// 
        /// Payment: All reserved balances on the account are returned.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a registered
        /// identity.
        /// 
        /// Emits `IdentityCleared` if successful.
        /// 
        /// # <weight>
        /// - `O(R + S + X)`
        ///   - where `R` registrar-count (governance-bounded).
        ///   - where `S` subs-count (hard- and deposit-bounded).
        ///   - where `X` additional-field-count (deposit-bounded and code-bounded).
        /// - One balance-unreserve operation.
        /// - `2` storage reads and `S + 2` storage deletions.
        /// - One event.
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall ClearIdentity()
        {
            return new GenericExtrinsicCall("Identity", "clear_identity");
        }
        
        /// <summary>
        /// >> Extrinsic: request_judgement
        /// Request a judgement from a registrar.
        /// 
        /// Payment: At most `max_fee` will be reserved for payment to the registrar if judgement
        /// given.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a
        /// registered identity.
        /// 
        /// - `reg_index`: The index of the registrar whose judgement is requested.
        /// - `max_fee`: The maximum fee that may be paid. This should just be auto-populated as:
        /// 
        /// ```nocompile
        /// Self::registrars().get(reg_index).unwrap().fee
        /// ```
        /// 
        /// Emits `JudgementRequested` if successful.
        /// 
        /// # <weight>
        /// - `O(R + X)`.
        /// - One balance-reserve operation.
        /// - Storage: 1 read `O(R)`, 1 mutate `O(X + R)`.
        /// - One event.
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall RequestJudgement(BaseCom<U32> reg_index, BaseCom<U128> max_fee)
        {
            return new GenericExtrinsicCall("Identity", "request_judgement", reg_index, max_fee);
        }
        
        /// <summary>
        /// >> Extrinsic: cancel_request
        /// Cancel a previous request.
        /// 
        /// Payment: A previously reserved deposit is returned on success.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a
        /// registered identity.
        /// 
        /// - `reg_index`: The index of the registrar whose judgement is no longer requested.
        /// 
        /// Emits `JudgementUnrequested` if successful.
        /// 
        /// # <weight>
        /// - `O(R + X)`.
        /// - One balance-reserve operation.
        /// - One storage mutation `O(R + X)`.
        /// - One event
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall CancelRequest(U32 reg_index)
        {
            return new GenericExtrinsicCall("Identity", "cancel_request", reg_index);
        }
        
        /// <summary>
        /// >> Extrinsic: set_fee
        /// Set the fee required for a judgement to be requested from a registrar.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must be the account
        /// of the registrar whose index is `index`.
        /// 
        /// - `index`: the index of the registrar whose fee is to be set.
        /// - `fee`: the new fee.
        /// 
        /// # <weight>
        /// - `O(R)`.
        /// - One storage mutation `O(R)`.
        /// - Benchmark: 7.315 + R * 0.329 ��s (min squares analysis)
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall SetFee(BaseCom<U32> index, BaseCom<U128> fee)
        {
            return new GenericExtrinsicCall("Identity", "set_fee", index, fee);
        }
        
        /// <summary>
        /// >> Extrinsic: set_account_id
        /// Change the account associated with a registrar.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must be the account
        /// of the registrar whose index is `index`.
        /// 
        /// - `index`: the index of the registrar whose fee is to be set.
        /// - `new`: the new account ID.
        /// 
        /// # <weight>
        /// - `O(R)`.
        /// - One storage mutation `O(R)`.
        /// - Benchmark: 8.823 + R * 0.32 ��s (min squares analysis)
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall SetAccountId(BaseCom<U32> index, AccountId32 @new)
        {
            return new GenericExtrinsicCall("Identity", "set_account_id", index, @new);
        }
        
        /// <summary>
        /// >> Extrinsic: set_fields
        /// Set the field information for a registrar.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must be the account
        /// of the registrar whose index is `index`.
        /// 
        /// - `index`: the index of the registrar whose fee is to be set.
        /// - `fields`: the fields that the registrar concerns themselves with.
        /// 
        /// # <weight>
        /// - `O(R)`.
        /// - One storage mutation `O(R)`.
        /// - Benchmark: 7.464 + R * 0.325 ��s (min squares analysis)
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall SetFields(BaseCom<U32> index, BitFlags fields)
        {
            return new GenericExtrinsicCall("Identity", "set_fields", index, fields);
        }
        
        /// <summary>
        /// >> Extrinsic: provide_judgement
        /// Provide a judgement for an account's identity.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must be the account
        /// of the registrar whose index is `reg_index`.
        /// 
        /// - `reg_index`: the index of the registrar whose judgement is being made.
        /// - `target`: the account whose identity the judgement is upon. This must be an account
        ///   with a registered identity.
        /// - `judgement`: the judgement of the registrar of index `reg_index` about `target`.
        /// 
        /// Emits `JudgementGiven` if successful.
        /// 
        /// # <weight>
        /// - `O(R + X)`.
        /// - One balance-transfer operation.
        /// - Up to one account-lookup operation.
        /// - Storage: 1 read `O(R)`, 1 mutate `O(R + X)`.
        /// - One event.
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall ProvideJudgement(BaseCom<U32> reg_index, EnumMultiAddress target, EnumJudgement judgement)
        {
            return new GenericExtrinsicCall("Identity", "provide_judgement", reg_index, target, judgement);
        }
        
        /// <summary>
        /// >> Extrinsic: kill_identity
        /// Remove an account's identity and sub-account information and slash the deposits.
        /// 
        /// Payment: Reserved balances from `set_subs` and `set_identity` are slashed and handled by
        /// `Slash`. Verification request deposits are not returned; they should be cancelled
        /// manually using `cancel_request`.
        /// 
        /// The dispatch origin for this call must match `T::ForceOrigin`.
        /// 
        /// - `target`: the account whose identity the judgement is upon. This must be an account
        ///   with a registered identity.
        /// 
        /// Emits `IdentityKilled` if successful.
        /// 
        /// # <weight>
        /// - `O(R + S + X)`.
        /// - One balance-reserve operation.
        /// - `S + 2` storage mutations.
        /// - One event.
        /// # </weight>
        /// </summary>
        public GenericExtrinsicCall KillIdentity(EnumMultiAddress target)
        {
            return new GenericExtrinsicCall("Identity", "kill_identity", target);
        }
        
        /// <summary>
        /// >> Extrinsic: add_sub
        /// Add the given account to the sender's subs.
        /// 
        /// Payment: Balance reserved by a previous `set_subs` call for one sub will be repatriated
        /// to the sender.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a registered
        /// sub identity of `sub`.
        /// </summary>
        public GenericExtrinsicCall AddSub(EnumMultiAddress sub, EnumData data)
        {
            return new GenericExtrinsicCall("Identity", "add_sub", sub, data);
        }
        
        /// <summary>
        /// >> Extrinsic: rename_sub
        /// Alter the associated name of the given sub-account.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a registered
        /// sub identity of `sub`.
        /// </summary>
        public GenericExtrinsicCall RenameSub(EnumMultiAddress sub, EnumData data)
        {
            return new GenericExtrinsicCall("Identity", "rename_sub", sub, data);
        }
        
        /// <summary>
        /// >> Extrinsic: remove_sub
        /// Remove the given account from the sender's subs.
        /// 
        /// Payment: Balance reserved by a previous `set_subs` call for one sub will be repatriated
        /// to the sender.
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a registered
        /// sub identity of `sub`.
        /// </summary>
        public GenericExtrinsicCall RemoveSub(EnumMultiAddress sub)
        {
            return new GenericExtrinsicCall("Identity", "remove_sub", sub);
        }
        
        /// <summary>
        /// >> Extrinsic: quit_sub
        /// Remove the sender as a sub-account.
        /// 
        /// Payment: Balance reserved by a previous `set_subs` call for one sub will be repatriated
        /// to the sender (*not* the original depositor).
        /// 
        /// The dispatch origin for this call must be _Signed_ and the sender must have a registered
        /// super-identity.
        /// 
        /// NOTE: This should not normally be used, but is provided in the case that the non-
        /// controller of an account is maliciously registered as a sub-account.
        /// </summary>
        public GenericExtrinsicCall QuitSub()
        {
            return new GenericExtrinsicCall("Identity", "quit_sub");
        }
    }
}
