//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletBounties
{
    
    
    /// <summary>
    /// >> Path: pallet_bounties.Bounty
    /// </summary>
    public sealed class Bounty : BaseType
    {
        
        private SubstrateNetApi.Model.SpCore.AccountId32 _proposer;
        
        private SubstrateNetApi.Model.Types.Primitive.U128 _value;
        
        private SubstrateNetApi.Model.Types.Primitive.U128 _fee;
        
        private SubstrateNetApi.Model.Types.Primitive.U128 _curatorDeposit;
        
        private SubstrateNetApi.Model.Types.Primitive.U128 _bond;
        
        private SubstrateNetApi.Model.PalletBounties.EnumBountyStatus _status;
        
        public SubstrateNetApi.Model.SpCore.AccountId32 Proposer
        {
            get
            {
                return this._proposer;
            }
            set
            {
                this._proposer = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U128 Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U128 Fee
        {
            get
            {
                return this._fee;
            }
            set
            {
                this._fee = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U128 CuratorDeposit
        {
            get
            {
                return this._curatorDeposit;
            }
            set
            {
                this._curatorDeposit = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U128 Bond
        {
            get
            {
                return this._bond;
            }
            set
            {
                this._bond = value;
            }
        }
        
        public SubstrateNetApi.Model.PalletBounties.EnumBountyStatus Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }
        
        public override string TypeName()
        {
            return "Bounty";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Proposer.Encode());
            result.AddRange(Value.Encode());
            result.AddRange(Fee.Encode());
            result.AddRange(CuratorDeposit.Encode());
            result.AddRange(Bond.Encode());
            result.AddRange(Status.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Proposer = new SubstrateNetApi.Model.SpCore.AccountId32();
            Proposer.Decode(byteArray, ref p);
            Value = new SubstrateNetApi.Model.Types.Primitive.U128();
            Value.Decode(byteArray, ref p);
            Fee = new SubstrateNetApi.Model.Types.Primitive.U128();
            Fee.Decode(byteArray, ref p);
            CuratorDeposit = new SubstrateNetApi.Model.Types.Primitive.U128();
            CuratorDeposit.Decode(byteArray, ref p);
            Bond = new SubstrateNetApi.Model.Types.Primitive.U128();
            Bond.Decode(byteArray, ref p);
            Status = new SubstrateNetApi.Model.PalletBounties.EnumBountyStatus();
            Status.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
