//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Extrinsics;
using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.PalletBounties;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.SpRuntime;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletBounties
{
    
    
    public sealed class BountiesStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public BountiesStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        public static string BountyCountParams()
        {
            return RequestGenerator.GetStorage("Bounties", "BountyCount", SubstrateNetApi.Model.Meta.Storage.Type.Plain);
        }
        
        /// <summary>
        /// >> BountyCount
        ///  Number of bounty proposals that have been made.
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> BountyCount(CancellationToken token)
        {
            string parameters = BountiesStorage.BountyCountParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string BountiesParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            return RequestGenerator.GetStorage("Bounties", "Bounties", SubstrateNetApi.Model.Meta.Storage.Type.Map, new SubstrateNetApi.Model.Meta.Storage.Hasher[] {
                        SubstrateNetApi.Model.Meta.Storage.Hasher.Twox64Concat}, new SubstrateNetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> Bounties
        ///  Bounties that have been made.
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletBounties.Bounty> Bounties(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = BountiesStorage.BountiesParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletBounties.Bounty>(parameters, token);
        }
        
        public static string BountyDescriptionsParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            return RequestGenerator.GetStorage("Bounties", "BountyDescriptions", SubstrateNetApi.Model.Meta.Storage.Type.Map, new SubstrateNetApi.Model.Meta.Storage.Hasher[] {
                        SubstrateNetApi.Model.Meta.Storage.Hasher.Twox64Concat}, new SubstrateNetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> BountyDescriptions
        ///  The description of each bounty.
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>> BountyDescriptions(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = BountiesStorage.BountyDescriptionsParams(key);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>>(parameters, token);
        }
        
        public static string BountyApprovalsParams()
        {
            return RequestGenerator.GetStorage("Bounties", "BountyApprovals", SubstrateNetApi.Model.Meta.Storage.Type.Plain);
        }
        
        /// <summary>
        /// >> BountyApprovals
        ///  Bounty indices that have been approved but not yet funded.
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.Types.Primitive.U32>> BountyApprovals(CancellationToken token)
        {
            string parameters = BountiesStorage.BountyApprovalsParams();
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.Types.Primitive.U32>>(parameters, token);
        }
    }
    
    public sealed class BountiesCalls
    {
        
        /// <summary>
        /// >> propose_bounty
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ProposeBounty(BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> value, BaseVec<SubstrateNetApi.Model.Types.Primitive.U8> description)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(value.Encode());
            byteArray.AddRange(description.Encode());
            return new Method(32, "Bounties", 0, "propose_bounty", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> approve_bounty
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ApproveBounty(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            return new Method(32, "Bounties", 1, "approve_bounty", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> propose_curator
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ProposeCurator(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress curator, BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> fee)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            byteArray.AddRange(curator.Encode());
            byteArray.AddRange(fee.Encode());
            return new Method(32, "Bounties", 2, "propose_curator", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> unassign_curator
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method UnassignCurator(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            return new Method(32, "Bounties", 3, "unassign_curator", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> accept_curator
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method AcceptCurator(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            return new Method(32, "Bounties", 4, "accept_curator", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> award_bounty
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method AwardBounty(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress beneficiary)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            byteArray.AddRange(beneficiary.Encode());
            return new Method(32, "Bounties", 5, "award_bounty", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> claim_bounty
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ClaimBounty(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            return new Method(32, "Bounties", 6, "claim_bounty", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> close_bounty
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method CloseBounty(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            return new Method(32, "Bounties", 7, "close_bounty", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> extend_bounty_expiry
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ExtendBountyExpiry(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> bounty_id, BaseVec<SubstrateNetApi.Model.Types.Primitive.U8> remark)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(bounty_id.Encode());
            byteArray.AddRange(remark.Encode());
            return new Method(32, "Bounties", 8, "extend_bounty_expiry", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> BountyProposed
    /// New bounty proposal. \[index\]
    /// </summary>
    public sealed class EventBountyProposed : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> BountyRejected
    /// A bounty proposal was rejected; funds were slashed. \[index, bond\]
    /// </summary>
    public sealed class EventBountyRejected : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> BountyBecameActive
    /// A bounty proposal is funded and became active. \[index\]
    /// </summary>
    public sealed class EventBountyBecameActive : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> BountyAwarded
    /// A bounty is awarded to a beneficiary. \[index, beneficiary\]
    /// </summary>
    public sealed class EventBountyAwarded : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> BountyClaimed
    /// A bounty is claimed by beneficiary. \[index, payout, beneficiary\]
    /// </summary>
    public sealed class EventBountyClaimed : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.Types.Primitive.U128, SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> BountyCanceled
    /// A bounty is cancelled. \[index\]
    /// </summary>
    public sealed class EventBountyCanceled : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> BountyExtended
    /// A bounty expiry is extended. \[index\]
    /// </summary>
    public sealed class EventBountyExtended : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    public enum BountiesErrors
    {
        
        /// <summary>
        /// >> InsufficientProposersBalance
        /// Proposer's balance is too low.
        /// </summary>
        InsufficientProposersBalance,
        
        /// <summary>
        /// >> InvalidIndex
        /// No proposal or bounty at that index.
        /// </summary>
        InvalidIndex,
        
        /// <summary>
        /// >> ReasonTooBig
        /// The reason given is just too big.
        /// </summary>
        ReasonTooBig,
        
        /// <summary>
        /// >> UnexpectedStatus
        /// The bounty status is unexpected.
        /// </summary>
        UnexpectedStatus,
        
        /// <summary>
        /// >> RequireCurator
        /// Require bounty curator.
        /// </summary>
        RequireCurator,
        
        /// <summary>
        /// >> InvalidValue
        /// Invalid bounty value.
        /// </summary>
        InvalidValue,
        
        /// <summary>
        /// >> InvalidFee
        /// Invalid bounty fee.
        /// </summary>
        InvalidFee,
        
        /// <summary>
        /// >> PendingPayout
        /// A bounty payout is pending.
        /// To cancel the bounty, you must unassign and slash the curator.
        /// </summary>
        PendingPayout,
        
        /// <summary>
        /// >> Premature
        /// The bounties cannot be claimed/closed because it's still in the countdown period.
        /// </summary>
        Premature,
    }
}
