//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletIndices
{
    
    
    /// <summary>
    /// >> Path: pallet_indices.pallet.Event
    /// 
    ///			The [event](https://substrate.dev/docs/en/knowledgebase/runtime/events) emitted
    ///			by this pallet.
    ///			
    /// </summary>
    public sealed class PalletIndicesEvent
    {
        
        /// <summary>
        /// >> Event: IndexAssigned
        /// A account index was assigned. \[index, who\]
        /// </summary>
        public sealed class IndexAssigned : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
        
        /// <summary>
        /// >> Event: IndexFreed
        /// A account index has been freed up (unassigned). \[index\]
        /// </summary>
        public sealed class IndexFreed : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
        
        /// <summary>
        /// >> Event: IndexFrozen
        /// A account index has been frozen to its current account ID. \[index, who\]
        /// </summary>
        public sealed class IndexFrozen : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
    }
}
