//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletBalances
{
    
    
    /// <summary>
    /// >> Path: pallet_balances.BalanceLock
    /// </summary>
    public sealed class BalanceLock : BaseType
    {
        
        private SubstrateNetApi.Model.Base.Arr8Special7 _id;
        
        private SubstrateNetApi.Model.Types.Primitive.U128 _amount;
        
        private SubstrateNetApi.Model.PalletBalances.EnumReasons _reasons;
        
        public SubstrateNetApi.Model.Base.Arr8Special7 Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U128 Amount
        {
            get
            {
                return this._amount;
            }
            set
            {
                this._amount = value;
            }
        }
        
        public SubstrateNetApi.Model.PalletBalances.EnumReasons Reasons
        {
            get
            {
                return this._reasons;
            }
            set
            {
                this._reasons = value;
            }
        }
        
        public override string TypeName()
        {
            return "BalanceLock";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Id.Encode());
            result.AddRange(Amount.Encode());
            result.AddRange(Reasons.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Id = new SubstrateNetApi.Model.Base.Arr8Special7();
            Id.Decode(byteArray, ref p);
            Amount = new SubstrateNetApi.Model.Types.Primitive.U128();
            Amount.Decode(byteArray, ref p);
            Reasons = new SubstrateNetApi.Model.PalletBalances.EnumReasons();
            Reasons.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
