//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletBabe
{
    
    
    /// <summary>
    /// >> 313 - Variant[pallet_babe.pallet.Error]
    /// 
    ///			Custom [dispatch errors](https://substrate.dev/docs/en/knowledgebase/runtime/errors)
    ///			of this pallet.
    ///			
    /// </summary>
    public enum PalletBabeError
    {
        
        /// <summary>
        /// >> InvalidEquivocationProof
        /// </summary>
        InvalidEquivocationProof,
        
        /// <summary>
        /// >> InvalidKeyOwnershipProof
        /// </summary>
        InvalidKeyOwnershipProof,
        
        /// <summary>
        /// >> DuplicateOffenceReport
        /// </summary>
        DuplicateOffenceReport,
    }
}
