//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Composite;
using SubstrateNetApi.Model.Types.Enum;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.Sequence;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.Composite
{
    
    
    /// <summary>
    /// >> Path: sp_consensus_slots.EquivocationProof
    /// </summary>
    public sealed class EquivocationProof : BaseType
    {
        
        private Public _offender;
        
        private Slot _slot;
        
        private Header _firstHeader;
        
        private Header _secondHeader;
        
        public Public Offender
        {
            get
            {
                return this._offender;
            }
            set
            {
                this._offender = value;
            }
        }
        
        public Slot Slot
        {
            get
            {
                return this._slot;
            }
            set
            {
                this._slot = value;
            }
        }
        
        public Header FirstHeader
        {
            get
            {
                return this._firstHeader;
            }
            set
            {
                this._firstHeader = value;
            }
        }
        
        public Header SecondHeader
        {
            get
            {
                return this._secondHeader;
            }
            set
            {
                this._secondHeader = value;
            }
        }
        
        public override string TypeName()
        {
            return "EquivocationProof";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Offender.Encode());
            result.AddRange(Slot.Encode());
            result.AddRange(FirstHeader.Encode());
            result.AddRange(SecondHeader.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Offender = new Public();
            Offender.Decode(byteArray, ref p);
            Slot = new Slot();
            Slot.Decode(byteArray, ref p);
            FirstHeader = new Header();
            FirstHeader.Decode(byteArray, ref p);
            SecondHeader = new Header();
            SecondHeader.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
