//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Composite;
using SubstrateNetApi.Model.Types.Enum;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.Sequence;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.Composite
{
    
    
    /// <summary>
    /// >> Path: frame_support.weights.WeightToFeeCoefficient
    /// </summary>
    public sealed class WeightToFeeCoefficient : BaseType
    {
        
        private U128 _coeffInteger;
        
        private Perbill _coeffFrac;
        
        private Bool _negative;
        
        private U8 _degree;
        
        public U128 CoeffInteger
        {
            get
            {
                return this._coeffInteger;
            }
            set
            {
                this._coeffInteger = value;
            }
        }
        
        public Perbill CoeffFrac
        {
            get
            {
                return this._coeffFrac;
            }
            set
            {
                this._coeffFrac = value;
            }
        }
        
        public Bool Negative
        {
            get
            {
                return this._negative;
            }
            set
            {
                this._negative = value;
            }
        }
        
        public U8 Degree
        {
            get
            {
                return this._degree;
            }
            set
            {
                this._degree = value;
            }
        }
        
        public override string TypeName()
        {
            return "WeightToFeeCoefficient";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(CoeffInteger.Encode());
            result.AddRange(CoeffFrac.Encode());
            result.AddRange(Negative.Encode());
            result.AddRange(Degree.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            CoeffInteger = new U128();
            CoeffInteger.Decode(byteArray, ref p);
            CoeffFrac = new Perbill();
            CoeffFrac.Decode(byteArray, ref p);
            Negative = new Bool();
            Negative.Decode(byteArray, ref p);
            Degree = new U8();
            Degree.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
