//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletDemocracy
{
    
    
    public enum AccountVote
    {
        
        Standard,
        
        Split,
    }
    
    /// <summary>
    /// >> Enum
    /// </summary>
    public sealed class EnumAccountVote : BaseEnumExt<AccountVote, BaseTuple<SubstrateNetApi.Model.PalletDemocracy.Vote, SubstrateNetApi.Model.Types.Primitive.U128>, BaseTuple<SubstrateNetApi.Model.Types.Primitive.U128, SubstrateNetApi.Model.Types.Primitive.U128>>
    {
    }
}
