//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Extrinsics;
using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.PalletStaking;
using SubstrateNetApi.Model.SpArithmetic;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.SpRuntime;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletStaking
{
    
    
    public sealed class StakingStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public StakingStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        public static string HistoryDepthParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "HistoryDepth", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> HistoryDepth
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> HistoryDepth(CancellationToken token)
        {
            string parameters = StakingStorage.HistoryDepthParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string ValidatorCountParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "ValidatorCount", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> ValidatorCount
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> ValidatorCount(CancellationToken token)
        {
            string parameters = StakingStorage.ValidatorCountParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string MinimumValidatorCountParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "MinimumValidatorCount", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> MinimumValidatorCount
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> MinimumValidatorCount(CancellationToken token)
        {
            string parameters = StakingStorage.MinimumValidatorCountParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string InvulnerablesParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "Invulnerables", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> Invulnerables
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.SpCore.AccountId32>> Invulnerables(CancellationToken token)
        {
            string parameters = StakingStorage.InvulnerablesParams();
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.SpCore.AccountId32>>(parameters, token);
        }
        
        public static string BondedParams(SubstrateNetApi.Model.SpCore.AccountId32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "Bonded", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Bonded
        /// </summary>
        public async Task<SubstrateNetApi.Model.SpCore.AccountId32> Bonded(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            string parameters = StakingStorage.BondedParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.SpCore.AccountId32>(parameters, token);
        }
        
        public static string MinNominatorBondParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "MinNominatorBond", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> MinNominatorBond
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U128> MinNominatorBond(CancellationToken token)
        {
            string parameters = StakingStorage.MinNominatorBondParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U128>(parameters, token);
        }
        
        public static string MinValidatorBondParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "MinValidatorBond", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> MinValidatorBond
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U128> MinValidatorBond(CancellationToken token)
        {
            string parameters = StakingStorage.MinValidatorBondParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U128>(parameters, token);
        }
        
        public static string LedgerParams(SubstrateNetApi.Model.SpCore.AccountId32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "Ledger", Storage.Type.Map, new[] {Storage.Hasher.BlakeTwo128Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Ledger
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.StakingLedger> Ledger(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            string parameters = StakingStorage.LedgerParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.StakingLedger>(parameters, token);
        }
        
        public static string PayeeParams(SubstrateNetApi.Model.SpCore.AccountId32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "Payee", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Payee
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.EnumRewardDestination> Payee(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            string parameters = StakingStorage.PayeeParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.EnumRewardDestination>(parameters, token);
        }
        
        public static string ValidatorsParams(SubstrateNetApi.Model.SpCore.AccountId32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "Validators", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Validators
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.ValidatorPrefs> Validators(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            string parameters = StakingStorage.ValidatorsParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.ValidatorPrefs>(parameters, token);
        }
        
        public static string CounterForValidatorsParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "CounterForValidators", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> CounterForValidators
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> CounterForValidators(CancellationToken token)
        {
            string parameters = StakingStorage.CounterForValidatorsParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string MaxValidatorsCountParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "MaxValidatorsCount", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> MaxValidatorsCount
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> MaxValidatorsCount(CancellationToken token)
        {
            string parameters = StakingStorage.MaxValidatorsCountParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string NominatorsParams(SubstrateNetApi.Model.SpCore.AccountId32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "Nominators", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> Nominators
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.Nominations> Nominators(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            string parameters = StakingStorage.NominatorsParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.Nominations>(parameters, token);
        }
        
        public static string CounterForNominatorsParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "CounterForNominators", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> CounterForNominators
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> CounterForNominators(CancellationToken token)
        {
            string parameters = StakingStorage.CounterForNominatorsParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string MaxNominatorsCountParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "MaxNominatorsCount", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> MaxNominatorsCount
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> MaxNominatorsCount(CancellationToken token)
        {
            string parameters = StakingStorage.MaxNominatorsCountParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string CurrentEraParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "CurrentEra", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> CurrentEra
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> CurrentEra(CancellationToken token)
        {
            string parameters = StakingStorage.CurrentEraParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string ActiveEraParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "ActiveEra", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> ActiveEra
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.ActiveEraInfo> ActiveEra(CancellationToken token)
        {
            string parameters = StakingStorage.ActiveEraParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.ActiveEraInfo>(parameters, token);
        }
        
        public static string ErasStartSessionIndexParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "ErasStartSessionIndex", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasStartSessionIndex
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> ErasStartSessionIndex(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasStartSessionIndexParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string ErasStakersParams(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key)
        {
            var keyParams = key.Value;
            var parameters = RequestGenerator.GetStorage("Staking", "ErasStakers", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat,Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasStakers
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.Exposure> ErasStakers(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasStakersParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.Exposure>(parameters, token);
        }
        
        public static string ErasStakersClippedParams(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key)
        {
            var keyParams = key.Value;
            var parameters = RequestGenerator.GetStorage("Staking", "ErasStakersClipped", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat,Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasStakersClipped
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.Exposure> ErasStakersClipped(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasStakersClippedParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.Exposure>(parameters, token);
        }
        
        public static string ErasValidatorPrefsParams(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key)
        {
            var keyParams = key.Value;
            var parameters = RequestGenerator.GetStorage("Staking", "ErasValidatorPrefs", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat,Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasValidatorPrefs
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.ValidatorPrefs> ErasValidatorPrefs(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasValidatorPrefsParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.ValidatorPrefs>(parameters, token);
        }
        
        public static string ErasValidatorRewardParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "ErasValidatorReward", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasValidatorReward
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U128> ErasValidatorReward(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasValidatorRewardParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U128>(parameters, token);
        }
        
        public static string ErasRewardPointsParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "ErasRewardPoints", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasRewardPoints
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.EraRewardPoints> ErasRewardPoints(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasRewardPointsParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.EraRewardPoints>(parameters, token);
        }
        
        public static string ErasTotalStakeParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "ErasTotalStake", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ErasTotalStake
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U128> ErasTotalStake(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = StakingStorage.ErasTotalStakeParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U128>(parameters, token);
        }
        
        public static string ForceEraParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "ForceEra", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> ForceEra
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.EnumForcing> ForceEra(CancellationToken token)
        {
            string parameters = StakingStorage.ForceEraParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.EnumForcing>(parameters, token);
        }
        
        public static string SlashRewardFractionParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "SlashRewardFraction", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> SlashRewardFraction
        /// </summary>
        public async Task<SubstrateNetApi.Model.SpArithmetic.Perbill> SlashRewardFraction(CancellationToken token)
        {
            string parameters = StakingStorage.SlashRewardFractionParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.SpArithmetic.Perbill>(parameters, token);
        }
        
        public static string CanceledSlashPayoutParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "CanceledSlashPayout", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> CanceledSlashPayout
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U128> CanceledSlashPayout(CancellationToken token)
        {
            string parameters = StakingStorage.CanceledSlashPayoutParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U128>(parameters, token);
        }
        
        public static string UnappliedSlashesParams(SubstrateNetApi.Model.Types.Primitive.U32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "UnappliedSlashes", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> UnappliedSlashes
        /// </summary>
        public async Task<BaseVec<SubstrateNetApi.Model.PalletStaking.UnappliedSlash>> UnappliedSlashes(SubstrateNetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = StakingStorage.UnappliedSlashesParams(key);
            return await _client.GetStorageAsync<BaseVec<SubstrateNetApi.Model.PalletStaking.UnappliedSlash>>(parameters, token);
        }
        
        public static string BondedErasParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "BondedEras", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> BondedEras
        /// </summary>
        public async Task<BaseVec<BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.Types.Primitive.U32>>> BondedEras(CancellationToken token)
        {
            string parameters = StakingStorage.BondedErasParams();
            return await _client.GetStorageAsync<BaseVec<BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.Types.Primitive.U32>>>(parameters, token);
        }
        
        public static string ValidatorSlashInEraParams(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key)
        {
            var keyParams = key.Value;
            var parameters = RequestGenerator.GetStorage("Staking", "ValidatorSlashInEra", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat,Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> ValidatorSlashInEra
        /// </summary>
        public async Task<BaseTuple<SubstrateNetApi.Model.SpArithmetic.Perbill,SubstrateNetApi.Model.Types.Primitive.U128>> ValidatorSlashInEra(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = StakingStorage.ValidatorSlashInEraParams(key);
            return await _client.GetStorageAsync<BaseTuple<SubstrateNetApi.Model.SpArithmetic.Perbill,SubstrateNetApi.Model.Types.Primitive.U128>>(parameters, token);
        }
        
        public static string NominatorSlashInEraParams(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key)
        {
            var keyParams = key.Value;
            var parameters = RequestGenerator.GetStorage("Staking", "NominatorSlashInEra", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat,Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> NominatorSlashInEra
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U128> NominatorSlashInEra(BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32,SubstrateNetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = StakingStorage.NominatorSlashInEraParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U128>(parameters, token);
        }
        
        public static string SlashingSpansParams(SubstrateNetApi.Model.SpCore.AccountId32 key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "SlashingSpans", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> SlashingSpans
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.SlashingSpans> SlashingSpans(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            string parameters = StakingStorage.SlashingSpansParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.SlashingSpans>(parameters, token);
        }
        
        public static string SpanSlashParams(BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U32> key)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Staking", "SpanSlash", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return parameters;
        }
        
        /// <summary>
        /// >> SpanSlash
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.SpanRecord> SpanSlash(BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32,SubstrateNetApi.Model.Types.Primitive.U32> key, CancellationToken token)
        {
            string parameters = StakingStorage.SpanSlashParams(key);
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.SpanRecord>(parameters, token);
        }
        
        public static string EarliestUnappliedSlashParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "EarliestUnappliedSlash", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> EarliestUnappliedSlash
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> EarliestUnappliedSlash(CancellationToken token)
        {
            string parameters = StakingStorage.EarliestUnappliedSlashParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string CurrentPlannedSessionParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "CurrentPlannedSession", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> CurrentPlannedSession
        /// </summary>
        public async Task<SubstrateNetApi.Model.Types.Primitive.U32> CurrentPlannedSession(CancellationToken token)
        {
            string parameters = StakingStorage.CurrentPlannedSessionParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.Types.Primitive.U32>(parameters, token);
        }
        
        public static string StorageVersionParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "StorageVersion", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> StorageVersion
        /// </summary>
        public async Task<SubstrateNetApi.Model.PalletStaking.EnumReleases> StorageVersion(CancellationToken token)
        {
            string parameters = StakingStorage.StorageVersionParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.PalletStaking.EnumReleases>(parameters, token);
        }
        
        public static string ChillThresholdParams()
        {
            var parameters = RequestGenerator.GetStorage("Staking", "ChillThreshold", Storage.Type.Plain);
            return parameters;
        }
        
        /// <summary>
        /// >> ChillThreshold
        /// </summary>
        public async Task<SubstrateNetApi.Model.SpArithmetic.Percent> ChillThreshold(CancellationToken token)
        {
            string parameters = StakingStorage.ChillThresholdParams();
            return await _client.GetStorageAsync<SubstrateNetApi.Model.SpArithmetic.Percent>(parameters, token);
        }
    }
    
    public sealed class StakingCalls
    {
        
        /// <summary>
        /// >> bond
        /// </summary>
        public static Method Bond(SubstrateNetApi.Model.SpRuntime.EnumMultiAddress controller, BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> value, SubstrateNetApi.Model.PalletStaking.EnumRewardDestination payee)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(controller.Encode());
            byteArray.AddRange(value.Encode());
            byteArray.AddRange(payee.Encode());
            return new Method(9, "Staking", 0, "bond", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> bond_extra
        /// </summary>
        public static Method BondExtra(BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> max_additional)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(max_additional.Encode());
            return new Method(9, "Staking", 1, "bond_extra", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> unbond
        /// </summary>
        public static Method Unbond(BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> value)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(value.Encode());
            return new Method(9, "Staking", 2, "unbond", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> withdraw_unbonded
        /// </summary>
        public static Method WithdrawUnbonded(SubstrateNetApi.Model.Types.Primitive.U32 num_slashing_spans)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(num_slashing_spans.Encode());
            return new Method(9, "Staking", 3, "withdraw_unbonded", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> validate
        /// </summary>
        public static Method Validate(SubstrateNetApi.Model.PalletStaking.ValidatorPrefs prefs)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(prefs.Encode());
            return new Method(9, "Staking", 4, "validate", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> nominate
        /// </summary>
        public static Method Nominate(BaseVec<SubstrateNetApi.Model.SpRuntime.EnumMultiAddress> targets)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(targets.Encode());
            return new Method(9, "Staking", 5, "nominate", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> chill
        /// </summary>
        public static Method Chill()
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            return new Method(9, "Staking", 6, "chill", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_payee
        /// </summary>
        public static Method SetPayee(SubstrateNetApi.Model.PalletStaking.EnumRewardDestination payee)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(payee.Encode());
            return new Method(9, "Staking", 7, "set_payee", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_controller
        /// </summary>
        public static Method SetController(SubstrateNetApi.Model.SpRuntime.EnumMultiAddress controller)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(controller.Encode());
            return new Method(9, "Staking", 8, "set_controller", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_validator_count
        /// </summary>
        public static Method SetValidatorCount(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @new)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(@new.Encode());
            return new Method(9, "Staking", 9, "set_validator_count", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> increase_validator_count
        /// </summary>
        public static Method IncreaseValidatorCount(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> additional)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(additional.Encode());
            return new Method(9, "Staking", 10, "increase_validator_count", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> scale_validator_count
        /// </summary>
        public static Method ScaleValidatorCount(SubstrateNetApi.Model.SpArithmetic.Percent factor)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(factor.Encode());
            return new Method(9, "Staking", 11, "scale_validator_count", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_no_eras
        /// </summary>
        public static Method ForceNoEras()
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            return new Method(9, "Staking", 12, "force_no_eras", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_new_era
        /// </summary>
        public static Method ForceNewEra()
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            return new Method(9, "Staking", 13, "force_new_era", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_invulnerables
        /// </summary>
        public static Method SetInvulnerables(BaseVec<SubstrateNetApi.Model.SpCore.AccountId32> invulnerables)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(invulnerables.Encode());
            return new Method(9, "Staking", 14, "set_invulnerables", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_unstake
        /// </summary>
        public static Method ForceUnstake(SubstrateNetApi.Model.SpCore.AccountId32 stash, SubstrateNetApi.Model.Types.Primitive.U32 num_slashing_spans)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(stash.Encode());
            byteArray.AddRange(num_slashing_spans.Encode());
            return new Method(9, "Staking", 15, "force_unstake", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_new_era_always
        /// </summary>
        public static Method ForceNewEraAlways()
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            return new Method(9, "Staking", 16, "force_new_era_always", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> cancel_deferred_slash
        /// </summary>
        public static Method CancelDeferredSlash(SubstrateNetApi.Model.Types.Primitive.U32 era, BaseVec<SubstrateNetApi.Model.Types.Primitive.U32> slash_indices)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(era.Encode());
            byteArray.AddRange(slash_indices.Encode());
            return new Method(9, "Staking", 17, "cancel_deferred_slash", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> payout_stakers
        /// </summary>
        public static Method PayoutStakers(SubstrateNetApi.Model.SpCore.AccountId32 validator_stash, SubstrateNetApi.Model.Types.Primitive.U32 era)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(validator_stash.Encode());
            byteArray.AddRange(era.Encode());
            return new Method(9, "Staking", 18, "payout_stakers", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> rebond
        /// </summary>
        public static Method Rebond(BaseCom<SubstrateNetApi.Model.Types.Primitive.U128> value)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(value.Encode());
            return new Method(9, "Staking", 19, "rebond", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_history_depth
        /// </summary>
        public static Method SetHistoryDepth(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> new_history_depth, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> era_items_deleted)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(new_history_depth.Encode());
            byteArray.AddRange(era_items_deleted.Encode());
            return new Method(9, "Staking", 20, "set_history_depth", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> reap_stash
        /// </summary>
        public static Method ReapStash(SubstrateNetApi.Model.SpCore.AccountId32 stash, SubstrateNetApi.Model.Types.Primitive.U32 num_slashing_spans)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(stash.Encode());
            byteArray.AddRange(num_slashing_spans.Encode());
            return new Method(9, "Staking", 21, "reap_stash", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> kick
        /// </summary>
        public static Method Kick(BaseVec<SubstrateNetApi.Model.SpRuntime.EnumMultiAddress> who)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(who.Encode());
            return new Method(9, "Staking", 22, "kick", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_staking_limits
        /// </summary>
        public static Method SetStakingLimits(SubstrateNetApi.Model.Types.Primitive.U128 min_nominator_bond, SubstrateNetApi.Model.Types.Primitive.U128 min_validator_bond, BaseOpt<SubstrateNetApi.Model.Types.Primitive.U32> max_nominator_count, BaseOpt<SubstrateNetApi.Model.Types.Primitive.U32> max_validator_count, BaseOpt<SubstrateNetApi.Model.SpArithmetic.Percent> threshold)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(min_nominator_bond.Encode());
            byteArray.AddRange(min_validator_bond.Encode());
            byteArray.AddRange(max_nominator_count.Encode());
            byteArray.AddRange(max_validator_count.Encode());
            byteArray.AddRange(threshold.Encode());
            return new Method(9, "Staking", 23, "set_staking_limits", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> chill_other
        /// </summary>
        public static Method ChillOther(SubstrateNetApi.Model.SpCore.AccountId32 controller)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(controller.Encode());
            return new Method(9, "Staking", 24, "chill_other", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> EraPaid
    /// </summary>
    public sealed class EventEraPaid : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.Types.Primitive.U128, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Rewarded
    /// </summary>
    public sealed class EventRewarded : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Slashed
    /// </summary>
    public sealed class EventSlashed : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> OldSlashingReportDiscarded
    /// </summary>
    public sealed class EventOldSlashingReportDiscarded : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> StakersElected
    /// </summary>
    public sealed class EventStakersElected : BaseTuple
    {
    }
    
    /// <summary>
    /// >> Bonded
    /// </summary>
    public sealed class EventBonded : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Unbonded
    /// </summary>
    public sealed class EventUnbonded : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Withdrawn
    /// </summary>
    public sealed class EventWithdrawn : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Kicked
    /// </summary>
    public sealed class EventKicked : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> StakingElectionFailed
    /// </summary>
    public sealed class EventStakingElectionFailed : BaseTuple
    {
    }
    
    /// <summary>
    /// >> Chilled
    /// </summary>
    public sealed class EventChilled : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> PayoutStarted
    /// </summary>
    public sealed class EventPayoutStarted : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
    {
    }
    
    public enum StakingErrors
    {
        
        /// <summary>
        /// >> NotController
        /// </summary>
        NotController,
        
        /// <summary>
        /// >> NotStash
        /// </summary>
        NotStash,
        
        /// <summary>
        /// >> AlreadyBonded
        /// </summary>
        AlreadyBonded,
        
        /// <summary>
        /// >> AlreadyPaired
        /// </summary>
        AlreadyPaired,
        
        /// <summary>
        /// >> EmptyTargets
        /// </summary>
        EmptyTargets,
        
        /// <summary>
        /// >> DuplicateIndex
        /// </summary>
        DuplicateIndex,
        
        /// <summary>
        /// >> InvalidSlashIndex
        /// </summary>
        InvalidSlashIndex,
        
        /// <summary>
        /// >> InsufficientBond
        /// </summary>
        InsufficientBond,
        
        /// <summary>
        /// >> NoMoreChunks
        /// </summary>
        NoMoreChunks,
        
        /// <summary>
        /// >> NoUnlockChunk
        /// </summary>
        NoUnlockChunk,
        
        /// <summary>
        /// >> FundedTarget
        /// </summary>
        FundedTarget,
        
        /// <summary>
        /// >> InvalidEraToReward
        /// </summary>
        InvalidEraToReward,
        
        /// <summary>
        /// >> InvalidNumberOfNominations
        /// </summary>
        InvalidNumberOfNominations,
        
        /// <summary>
        /// >> NotSortedAndUnique
        /// </summary>
        NotSortedAndUnique,
        
        /// <summary>
        /// >> AlreadyClaimed
        /// </summary>
        AlreadyClaimed,
        
        /// <summary>
        /// >> IncorrectHistoryDepth
        /// </summary>
        IncorrectHistoryDepth,
        
        /// <summary>
        /// >> IncorrectSlashingSpans
        /// </summary>
        IncorrectSlashingSpans,
        
        /// <summary>
        /// >> BadState
        /// </summary>
        BadState,
        
        /// <summary>
        /// >> TooManyTargets
        /// </summary>
        TooManyTargets,
        
        /// <summary>
        /// >> BadTarget
        /// </summary>
        BadTarget,
        
        /// <summary>
        /// >> CannotChillOther
        /// </summary>
        CannotChillOther,
        
        /// <summary>
        /// >> TooManyNominators
        /// </summary>
        TooManyNominators,
        
        /// <summary>
        /// >> TooManyValidators
        /// </summary>
        TooManyValidators,
    }
}
