//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Calls;
using SubstrateNetApi.Model.NodeRuntime;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletSession
{
    
    
    /// <summary>
    /// >> 206 - Variant[pallet_session.Call]
    /// Dispatchable calls.
    /// 
    /// Each variant of this enum maps to a dispatchable function from the associated module.
    /// </summary>
    public sealed class PalletSessionCall
    {
        
        /// <summary>
        /// >> set_keys
        /// </summary>
        public GenericExtrinsicCall SetKeys(SubstrateNetApi.Model.NodeRuntime.SessionKeys keys, BaseVec<SubstrateNetApi.Model.Types.Primitive.U8> proof)
        {
            return new GenericExtrinsicCall("Session", "set_keys", keys, proof);
        }
        
        /// <summary>
        /// >> purge_keys
        /// </summary>
        public GenericExtrinsicCall PurgeKeys()
        {
            return new GenericExtrinsicCall("Session", "purge_keys");
        }
    }
}
