//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi
{
    
    
    public sealed class SubstrateClientExt : SubstrateNetApi.SubstrateClient
    {
        
        // FrameSystemStorage storage calls.
        public SubstrateNetApi.Model.FrameSystem.FrameSystemStorage FrameSystemStorage;
        
        // PalletUtilityStorage storage calls.
        public SubstrateNetApi.Model.PalletUtility.PalletUtilityStorage PalletUtilityStorage;
        
        // PalletBabeStorage storage calls.
        public SubstrateNetApi.Model.PalletBabe.PalletBabeStorage PalletBabeStorage;
        
        // PalletTimestampStorage storage calls.
        public SubstrateNetApi.Model.PalletTimestamp.PalletTimestampStorage PalletTimestampStorage;
        
        // PalletAuthorshipStorage storage calls.
        public SubstrateNetApi.Model.PalletAuthorship.PalletAuthorshipStorage PalletAuthorshipStorage;
        
        // PalletIndicesStorage storage calls.
        public SubstrateNetApi.Model.PalletIndices.PalletIndicesStorage PalletIndicesStorage;
        
        // PalletBalancesStorage storage calls.
        public SubstrateNetApi.Model.PalletBalances.PalletBalancesStorage PalletBalancesStorage;
        
        // PalletTransactionPaymentStorage storage calls.
        public SubstrateNetApi.Model.PalletTransactionPayment.PalletTransactionPaymentStorage PalletTransactionPaymentStorage;
        
        // PalletElectionProviderMultiPhaseStorage storage calls.
        public SubstrateNetApi.Model.PalletElectionProviderMultiPhase.PalletElectionProviderMultiPhaseStorage PalletElectionProviderMultiPhaseStorage;
        
        // PalletStakingStorage storage calls.
        public SubstrateNetApi.Model.PalletStaking.PalletStakingStorage PalletStakingStorage;
        
        // PalletSessionStorage storage calls.
        public SubstrateNetApi.Model.PalletSession.PalletSessionStorage PalletSessionStorage;
        
        // PalletDemocracyStorage storage calls.
        public SubstrateNetApi.Model.PalletDemocracy.PalletDemocracyStorage PalletDemocracyStorage;
        
        // PalletCouncilStorage storage calls.
        public SubstrateNetApi.Model.PalletCouncil.PalletCouncilStorage PalletCouncilStorage;
        
        // PalletTechnicalCommitteeStorage storage calls.
        public SubstrateNetApi.Model.PalletTechnicalCommittee.PalletTechnicalCommitteeStorage PalletTechnicalCommitteeStorage;
        
        // PalletElectionsStorage storage calls.
        public SubstrateNetApi.Model.PalletElections.PalletElectionsStorage PalletElectionsStorage;
        
        // PalletTechnicalMembershipStorage storage calls.
        public SubstrateNetApi.Model.PalletTechnicalMembership.PalletTechnicalMembershipStorage PalletTechnicalMembershipStorage;
        
        // PalletGrandpaStorage storage calls.
        public SubstrateNetApi.Model.PalletGrandpa.PalletGrandpaStorage PalletGrandpaStorage;
        
        // PalletTreasuryStorage storage calls.
        public SubstrateNetApi.Model.PalletTreasury.PalletTreasuryStorage PalletTreasuryStorage;
        
        // PalletContractsStorage storage calls.
        public SubstrateNetApi.Model.PalletContracts.PalletContractsStorage PalletContractsStorage;
        
        // PalletSudoStorage storage calls.
        public SubstrateNetApi.Model.PalletSudo.PalletSudoStorage PalletSudoStorage;
        
        // PalletImOnlineStorage storage calls.
        public SubstrateNetApi.Model.PalletImOnline.PalletImOnlineStorage PalletImOnlineStorage;
        
        // PalletAuthorityDiscoveryStorage storage calls.
        public SubstrateNetApi.Model.PalletAuthorityDiscovery.PalletAuthorityDiscoveryStorage PalletAuthorityDiscoveryStorage;
        
        // PalletOffencesStorage storage calls.
        public SubstrateNetApi.Model.PalletOffences.PalletOffencesStorage PalletOffencesStorage;
        
        // PalletHistoricalStorage storage calls.
        public SubstrateNetApi.Model.PalletHistorical.PalletHistoricalStorage PalletHistoricalStorage;
        
        // PalletRandomnessCollectiveFlipStorage storage calls.
        public SubstrateNetApi.Model.PalletRandomnessCollectiveFlip.PalletRandomnessCollectiveFlipStorage PalletRandomnessCollectiveFlipStorage;
        
        // PalletIdentityStorage storage calls.
        public SubstrateNetApi.Model.PalletIdentity.PalletIdentityStorage PalletIdentityStorage;
        
        // PalletSocietyStorage storage calls.
        public SubstrateNetApi.Model.PalletSociety.PalletSocietyStorage PalletSocietyStorage;
        
        // PalletRecoveryStorage storage calls.
        public SubstrateNetApi.Model.PalletRecovery.PalletRecoveryStorage PalletRecoveryStorage;
        
        // PalletVestingStorage storage calls.
        public SubstrateNetApi.Model.PalletVesting.PalletVestingStorage PalletVestingStorage;
        
        // PalletSchedulerStorage storage calls.
        public SubstrateNetApi.Model.PalletScheduler.PalletSchedulerStorage PalletSchedulerStorage;
        
        // PalletProxyStorage storage calls.
        public SubstrateNetApi.Model.PalletProxy.PalletProxyStorage PalletProxyStorage;
        
        // PalletMultisigStorage storage calls.
        public SubstrateNetApi.Model.PalletMultisig.PalletMultisigStorage PalletMultisigStorage;
        
        // PalletBountiesStorage storage calls.
        public SubstrateNetApi.Model.PalletBounties.PalletBountiesStorage PalletBountiesStorage;
        
        // PalletTipsStorage storage calls.
        public SubstrateNetApi.Model.PalletTips.PalletTipsStorage PalletTipsStorage;
        
        // PalletAssetsStorage storage calls.
        public SubstrateNetApi.Model.PalletAssets.PalletAssetsStorage PalletAssetsStorage;
        
        // PalletMmrStorage storage calls.
        public SubstrateNetApi.Model.PalletMmr.PalletMmrStorage PalletMmrStorage;
        
        // PalletLotteryStorage storage calls.
        public SubstrateNetApi.Model.PalletLottery.PalletLotteryStorage PalletLotteryStorage;
        
        // PalletGiltStorage storage calls.
        public SubstrateNetApi.Model.PalletGilt.PalletGiltStorage PalletGiltStorage;
        
        // PalletUniquesStorage storage calls.
        public SubstrateNetApi.Model.PalletUniques.PalletUniquesStorage PalletUniquesStorage;
        
        // PalletTransactionStorageStorage storage calls.
        public SubstrateNetApi.Model.PalletTransactionStorage.PalletTransactionStorageStorage PalletTransactionStorageStorage;
        
        // PalletBagsListStorage storage calls.
        public SubstrateNetApi.Model.PalletBagsList.PalletBagsListStorage PalletBagsListStorage;
        
        public SubstrateClientExt(System.Uri uri) : 
                base(uri)
        {
            this.FrameSystemStorage = new SubstrateNetApi.Model.FrameSystem.FrameSystemStorage(this);
            this.PalletUtilityStorage = new SubstrateNetApi.Model.PalletUtility.PalletUtilityStorage(this);
            this.PalletBabeStorage = new SubstrateNetApi.Model.PalletBabe.PalletBabeStorage(this);
            this.PalletTimestampStorage = new SubstrateNetApi.Model.PalletTimestamp.PalletTimestampStorage(this);
            this.PalletAuthorshipStorage = new SubstrateNetApi.Model.PalletAuthorship.PalletAuthorshipStorage(this);
            this.PalletIndicesStorage = new SubstrateNetApi.Model.PalletIndices.PalletIndicesStorage(this);
            this.PalletBalancesStorage = new SubstrateNetApi.Model.PalletBalances.PalletBalancesStorage(this);
            this.PalletTransactionPaymentStorage = new SubstrateNetApi.Model.PalletTransactionPayment.PalletTransactionPaymentStorage(this);
            this.PalletElectionProviderMultiPhaseStorage = new SubstrateNetApi.Model.PalletElectionProviderMultiPhase.PalletElectionProviderMultiPhaseStorage(this);
            this.PalletStakingStorage = new SubstrateNetApi.Model.PalletStaking.PalletStakingStorage(this);
            this.PalletSessionStorage = new SubstrateNetApi.Model.PalletSession.PalletSessionStorage(this);
            this.PalletDemocracyStorage = new SubstrateNetApi.Model.PalletDemocracy.PalletDemocracyStorage(this);
            this.PalletCouncilStorage = new SubstrateNetApi.Model.PalletCouncil.PalletCouncilStorage(this);
            this.PalletTechnicalCommitteeStorage = new SubstrateNetApi.Model.PalletTechnicalCommittee.PalletTechnicalCommitteeStorage(this);
            this.PalletElectionsStorage = new SubstrateNetApi.Model.PalletElections.PalletElectionsStorage(this);
            this.PalletTechnicalMembershipStorage = new SubstrateNetApi.Model.PalletTechnicalMembership.PalletTechnicalMembershipStorage(this);
            this.PalletGrandpaStorage = new SubstrateNetApi.Model.PalletGrandpa.PalletGrandpaStorage(this);
            this.PalletTreasuryStorage = new SubstrateNetApi.Model.PalletTreasury.PalletTreasuryStorage(this);
            this.PalletContractsStorage = new SubstrateNetApi.Model.PalletContracts.PalletContractsStorage(this);
            this.PalletSudoStorage = new SubstrateNetApi.Model.PalletSudo.PalletSudoStorage(this);
            this.PalletImOnlineStorage = new SubstrateNetApi.Model.PalletImOnline.PalletImOnlineStorage(this);
            this.PalletAuthorityDiscoveryStorage = new SubstrateNetApi.Model.PalletAuthorityDiscovery.PalletAuthorityDiscoveryStorage(this);
            this.PalletOffencesStorage = new SubstrateNetApi.Model.PalletOffences.PalletOffencesStorage(this);
            this.PalletHistoricalStorage = new SubstrateNetApi.Model.PalletHistorical.PalletHistoricalStorage(this);
            this.PalletRandomnessCollectiveFlipStorage = new SubstrateNetApi.Model.PalletRandomnessCollectiveFlip.PalletRandomnessCollectiveFlipStorage(this);
            this.PalletIdentityStorage = new SubstrateNetApi.Model.PalletIdentity.PalletIdentityStorage(this);
            this.PalletSocietyStorage = new SubstrateNetApi.Model.PalletSociety.PalletSocietyStorage(this);
            this.PalletRecoveryStorage = new SubstrateNetApi.Model.PalletRecovery.PalletRecoveryStorage(this);
            this.PalletVestingStorage = new SubstrateNetApi.Model.PalletVesting.PalletVestingStorage(this);
            this.PalletSchedulerStorage = new SubstrateNetApi.Model.PalletScheduler.PalletSchedulerStorage(this);
            this.PalletProxyStorage = new SubstrateNetApi.Model.PalletProxy.PalletProxyStorage(this);
            this.PalletMultisigStorage = new SubstrateNetApi.Model.PalletMultisig.PalletMultisigStorage(this);
            this.PalletBountiesStorage = new SubstrateNetApi.Model.PalletBounties.PalletBountiesStorage(this);
            this.PalletTipsStorage = new SubstrateNetApi.Model.PalletTips.PalletTipsStorage(this);
            this.PalletAssetsStorage = new SubstrateNetApi.Model.PalletAssets.PalletAssetsStorage(this);
            this.PalletMmrStorage = new SubstrateNetApi.Model.PalletMmr.PalletMmrStorage(this);
            this.PalletLotteryStorage = new SubstrateNetApi.Model.PalletLottery.PalletLotteryStorage(this);
            this.PalletGiltStorage = new SubstrateNetApi.Model.PalletGilt.PalletGiltStorage(this);
            this.PalletUniquesStorage = new SubstrateNetApi.Model.PalletUniques.PalletUniquesStorage(this);
            this.PalletTransactionStorageStorage = new SubstrateNetApi.Model.PalletTransactionStorage.PalletTransactionStorageStorage(this);
            this.PalletBagsListStorage = new SubstrateNetApi.Model.PalletBagsList.PalletBagsListStorage(this);
        }
    }
}
