//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi
{
    
    
    public sealed class SubstrateClientExt : SubstrateNetApi.SubstrateClient
    {
        
        /// <summary>
        /// StorageKeyDict for key definition informations.
        /// </summary>
        public System.Collections.Generic.Dictionary<System.Tuple<string, string>, System.Tuple<SubstrateNetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>> StorageKeyDict;
        
        /// <summary>
        /// SystemStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.FrameSystem.SystemStorage SystemStorage;
        
        /// <summary>
        /// UtilityStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletUtility.UtilityStorage UtilityStorage;
        
        /// <summary>
        /// BabeStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletBabe.BabeStorage BabeStorage;
        
        /// <summary>
        /// TimestampStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTimestamp.TimestampStorage TimestampStorage;
        
        /// <summary>
        /// AuthorshipStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletAuthorship.AuthorshipStorage AuthorshipStorage;
        
        /// <summary>
        /// IndicesStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletIndices.IndicesStorage IndicesStorage;
        
        /// <summary>
        /// BalancesStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletBalances.BalancesStorage BalancesStorage;
        
        /// <summary>
        /// TransactionPaymentStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTransactionPayment.TransactionPaymentStorage TransactionPaymentStorage;
        
        /// <summary>
        /// ElectionProviderMultiPhaseStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletElectionProviderMultiPhase.ElectionProviderMultiPhaseStorage ElectionProviderMultiPhaseStorage;
        
        /// <summary>
        /// StakingStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletStaking.StakingStorage StakingStorage;
        
        /// <summary>
        /// SessionStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletSession.SessionStorage SessionStorage;
        
        /// <summary>
        /// DemocracyStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletDemocracy.DemocracyStorage DemocracyStorage;
        
        /// <summary>
        /// CouncilStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletCouncil.CouncilStorage CouncilStorage;
        
        /// <summary>
        /// TechnicalCommitteeStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTechnicalCommittee.TechnicalCommitteeStorage TechnicalCommitteeStorage;
        
        /// <summary>
        /// ElectionsStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletElections.ElectionsStorage ElectionsStorage;
        
        /// <summary>
        /// TechnicalMembershipStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTechnicalMembership.TechnicalMembershipStorage TechnicalMembershipStorage;
        
        /// <summary>
        /// GrandpaStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletGrandpa.GrandpaStorage GrandpaStorage;
        
        /// <summary>
        /// TreasuryStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTreasury.TreasuryStorage TreasuryStorage;
        
        /// <summary>
        /// ContractsStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletContracts.ContractsStorage ContractsStorage;
        
        /// <summary>
        /// SudoStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletSudo.SudoStorage SudoStorage;
        
        /// <summary>
        /// ImOnlineStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletImOnline.ImOnlineStorage ImOnlineStorage;
        
        /// <summary>
        /// AuthorityDiscoveryStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletAuthorityDiscovery.AuthorityDiscoveryStorage AuthorityDiscoveryStorage;
        
        /// <summary>
        /// OffencesStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletOffences.OffencesStorage OffencesStorage;
        
        /// <summary>
        /// HistoricalStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletHistorical.HistoricalStorage HistoricalStorage;
        
        /// <summary>
        /// RandomnessCollectiveFlipStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletRandomnessCollectiveFlip.RandomnessCollectiveFlipStorage RandomnessCollectiveFlipStorage;
        
        /// <summary>
        /// IdentityStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletIdentity.IdentityStorage IdentityStorage;
        
        /// <summary>
        /// SocietyStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletSociety.SocietyStorage SocietyStorage;
        
        /// <summary>
        /// RecoveryStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletRecovery.RecoveryStorage RecoveryStorage;
        
        /// <summary>
        /// VestingStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletVesting.VestingStorage VestingStorage;
        
        /// <summary>
        /// SchedulerStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletScheduler.SchedulerStorage SchedulerStorage;
        
        /// <summary>
        /// ProxyStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletProxy.ProxyStorage ProxyStorage;
        
        /// <summary>
        /// MultisigStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletMultisig.MultisigStorage MultisigStorage;
        
        /// <summary>
        /// BountiesStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletBounties.BountiesStorage BountiesStorage;
        
        /// <summary>
        /// TipsStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTips.TipsStorage TipsStorage;
        
        /// <summary>
        /// AssetsStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletAssets.AssetsStorage AssetsStorage;
        
        /// <summary>
        /// MmrStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletMmr.MmrStorage MmrStorage;
        
        /// <summary>
        /// LotteryStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletLottery.LotteryStorage LotteryStorage;
        
        /// <summary>
        /// GiltStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletGilt.GiltStorage GiltStorage;
        
        /// <summary>
        /// UniquesStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletUniques.UniquesStorage UniquesStorage;
        
        /// <summary>
        /// TransactionStorageStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletTransactionStorage.TransactionStorageStorage TransactionStorageStorage;
        
        /// <summary>
        /// BagsListStorage storage calls.
        /// </summary>
        public SubstrateNetApi.Model.PalletBagsList.BagsListStorage BagsListStorage;
        
        public SubstrateClientExt(System.Uri uri) : 
                base(uri)
        {
            StorageKeyDict = new System.Collections.Generic.Dictionary<System.Tuple<string, string>, System.Tuple<SubstrateNetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>>();
            this.SystemStorage = new SubstrateNetApi.Model.FrameSystem.SystemStorage(this);
            this.UtilityStorage = new SubstrateNetApi.Model.PalletUtility.UtilityStorage(this);
            this.BabeStorage = new SubstrateNetApi.Model.PalletBabe.BabeStorage(this);
            this.TimestampStorage = new SubstrateNetApi.Model.PalletTimestamp.TimestampStorage(this);
            this.AuthorshipStorage = new SubstrateNetApi.Model.PalletAuthorship.AuthorshipStorage(this);
            this.IndicesStorage = new SubstrateNetApi.Model.PalletIndices.IndicesStorage(this);
            this.BalancesStorage = new SubstrateNetApi.Model.PalletBalances.BalancesStorage(this);
            this.TransactionPaymentStorage = new SubstrateNetApi.Model.PalletTransactionPayment.TransactionPaymentStorage(this);
            this.ElectionProviderMultiPhaseStorage = new SubstrateNetApi.Model.PalletElectionProviderMultiPhase.ElectionProviderMultiPhaseStorage(this);
            this.StakingStorage = new SubstrateNetApi.Model.PalletStaking.StakingStorage(this);
            this.SessionStorage = new SubstrateNetApi.Model.PalletSession.SessionStorage(this);
            this.DemocracyStorage = new SubstrateNetApi.Model.PalletDemocracy.DemocracyStorage(this);
            this.CouncilStorage = new SubstrateNetApi.Model.PalletCouncil.CouncilStorage(this);
            this.TechnicalCommitteeStorage = new SubstrateNetApi.Model.PalletTechnicalCommittee.TechnicalCommitteeStorage(this);
            this.ElectionsStorage = new SubstrateNetApi.Model.PalletElections.ElectionsStorage(this);
            this.TechnicalMembershipStorage = new SubstrateNetApi.Model.PalletTechnicalMembership.TechnicalMembershipStorage(this);
            this.GrandpaStorage = new SubstrateNetApi.Model.PalletGrandpa.GrandpaStorage(this);
            this.TreasuryStorage = new SubstrateNetApi.Model.PalletTreasury.TreasuryStorage(this);
            this.ContractsStorage = new SubstrateNetApi.Model.PalletContracts.ContractsStorage(this);
            this.SudoStorage = new SubstrateNetApi.Model.PalletSudo.SudoStorage(this);
            this.ImOnlineStorage = new SubstrateNetApi.Model.PalletImOnline.ImOnlineStorage(this);
            this.AuthorityDiscoveryStorage = new SubstrateNetApi.Model.PalletAuthorityDiscovery.AuthorityDiscoveryStorage(this);
            this.OffencesStorage = new SubstrateNetApi.Model.PalletOffences.OffencesStorage(this);
            this.HistoricalStorage = new SubstrateNetApi.Model.PalletHistorical.HistoricalStorage(this);
            this.RandomnessCollectiveFlipStorage = new SubstrateNetApi.Model.PalletRandomnessCollectiveFlip.RandomnessCollectiveFlipStorage(this);
            this.IdentityStorage = new SubstrateNetApi.Model.PalletIdentity.IdentityStorage(this);
            this.SocietyStorage = new SubstrateNetApi.Model.PalletSociety.SocietyStorage(this);
            this.RecoveryStorage = new SubstrateNetApi.Model.PalletRecovery.RecoveryStorage(this);
            this.VestingStorage = new SubstrateNetApi.Model.PalletVesting.VestingStorage(this);
            this.SchedulerStorage = new SubstrateNetApi.Model.PalletScheduler.SchedulerStorage(this);
            this.ProxyStorage = new SubstrateNetApi.Model.PalletProxy.ProxyStorage(this);
            this.MultisigStorage = new SubstrateNetApi.Model.PalletMultisig.MultisigStorage(this);
            this.BountiesStorage = new SubstrateNetApi.Model.PalletBounties.BountiesStorage(this);
            this.TipsStorage = new SubstrateNetApi.Model.PalletTips.TipsStorage(this);
            this.AssetsStorage = new SubstrateNetApi.Model.PalletAssets.AssetsStorage(this);
            this.MmrStorage = new SubstrateNetApi.Model.PalletMmr.MmrStorage(this);
            this.LotteryStorage = new SubstrateNetApi.Model.PalletLottery.LotteryStorage(this);
            this.GiltStorage = new SubstrateNetApi.Model.PalletGilt.GiltStorage(this);
            this.UniquesStorage = new SubstrateNetApi.Model.PalletUniques.UniquesStorage(this);
            this.TransactionStorageStorage = new SubstrateNetApi.Model.PalletTransactionStorage.TransactionStorageStorage(this);
            this.BagsListStorage = new SubstrateNetApi.Model.PalletBagsList.BagsListStorage(this);
        }
    }
}
