//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletAssets
{
    
    
    /// <summary>
    /// >> Path: pallet_assets.types.AssetMetadata
    /// </summary>
    public sealed class AssetMetadata : BaseType
    {
        
        private SubstrateNetApi.Model.Types.Primitive.U128 _deposit;
        
        private SubstrateNetApi.Model.FrameSupport.BoundedVec _name;
        
        private SubstrateNetApi.Model.FrameSupport.BoundedVec _symbol;
        
        private SubstrateNetApi.Model.Types.Primitive.U8 _decimals;
        
        private SubstrateNetApi.Model.Types.Primitive.Bool _isFrozen;
        
        public SubstrateNetApi.Model.Types.Primitive.U128 Deposit
        {
            get
            {
                return this._deposit;
            }
            set
            {
                this._deposit = value;
            }
        }
        
        public SubstrateNetApi.Model.FrameSupport.BoundedVec Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        public SubstrateNetApi.Model.FrameSupport.BoundedVec Symbol
        {
            get
            {
                return this._symbol;
            }
            set
            {
                this._symbol = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U8 Decimals
        {
            get
            {
                return this._decimals;
            }
            set
            {
                this._decimals = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.Bool IsFrozen
        {
            get
            {
                return this._isFrozen;
            }
            set
            {
                this._isFrozen = value;
            }
        }
        
        public override string TypeName()
        {
            return "AssetMetadata";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Deposit.Encode());
            result.AddRange(Name.Encode());
            result.AddRange(Symbol.Encode());
            result.AddRange(Decimals.Encode());
            result.AddRange(IsFrozen.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Deposit = new SubstrateNetApi.Model.Types.Primitive.U128();
            Deposit.Decode(byteArray, ref p);
            Name = new SubstrateNetApi.Model.FrameSupport.BoundedVec();
            Name.Decode(byteArray, ref p);
            Symbol = new SubstrateNetApi.Model.FrameSupport.BoundedVec();
            Symbol.Decode(byteArray, ref p);
            Decimals = new SubstrateNetApi.Model.Types.Primitive.U8();
            Decimals.Decode(byteArray, ref p);
            IsFrozen = new SubstrateNetApi.Model.Types.Primitive.Bool();
            IsFrozen.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
