//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletAssets
{
    
    
    /// <summary>
    /// >> Path: pallet_assets.pallet.Event
    /// 
    ///			The [event](https://substrate.dev/docs/en/knowledgebase/runtime/events) emitted
    ///			by this pallet.
    ///			
    /// </summary>
    public sealed class PalletAssetsEvent
    {
        
        /// <summary>
        /// >> Event: Created
        /// Some asset class was created. \[asset_id, creator, owner\]
        /// </summary>
        public sealed class Created : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: Issued
        /// Some assets were issued. \[asset_id, owner, total_supply\]
        /// </summary>
        public sealed class Issued : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U64>
        {
        }
        
        /// <summary>
        /// >> Event: Transferred
        /// Some assets were transferred. \[asset_id, from, to, amount\]
        /// </summary>
        public sealed class Transferred : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U64>
        {
        }
        
        /// <summary>
        /// >> Event: Burned
        /// Some assets were destroyed. \[asset_id, owner, balance\]
        /// </summary>
        public sealed class Burned : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U64>
        {
        }
        
        /// <summary>
        /// >> Event: TeamChanged
        /// The management team changed \[asset_id, issuer, admin, freezer\]
        /// </summary>
        public sealed class TeamChanged : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: OwnerChanged
        /// The owner changed \[asset_id, owner\]
        /// </summary>
        public sealed class OwnerChanged : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: Frozen
        /// Some account `who` was frozen. \[asset_id, who\]
        /// </summary>
        public sealed class Frozen : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: Thawed
        /// Some account `who` was thawed. \[asset_id, who\]
        /// </summary>
        public sealed class Thawed : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: AssetFrozen
        /// Some asset `asset_id` was frozen. \[asset_id\]
        /// </summary>
        public sealed class AssetFrozen : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
        
        /// <summary>
        /// >> Event: AssetThawed
        /// Some asset `asset_id` was thawed. \[asset_id\]
        /// </summary>
        public sealed class AssetThawed : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
        
        /// <summary>
        /// >> Event: Destroyed
        /// An asset class was destroyed.
        /// </summary>
        public sealed class Destroyed : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
        
        /// <summary>
        /// >> Event: ForceCreated
        /// Some asset class was force-created. \[asset_id, owner\]
        /// </summary>
        public sealed class ForceCreated : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: MetadataSet
        /// New metadata has been set for an asset. \[asset_id, name, symbol, decimals, is_frozen\]
        /// </summary>
        public sealed class MetadataSet : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>, BaseVec<SubstrateNetApi.Model.Types.Primitive.U8>, SubstrateNetApi.Model.Types.Primitive.U8, SubstrateNetApi.Model.Types.Primitive.Bool>
        {
        }
        
        /// <summary>
        /// >> Event: MetadataCleared
        /// Metadata has been cleared for an asset. \[asset_id\]
        /// </summary>
        public sealed class MetadataCleared : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
        
        /// <summary>
        /// >> Event: ApprovedTransfer
        /// (Additional) funds have been approved for transfer to a destination account.
        /// \[asset_id, source, delegate, amount\]
        /// </summary>
        public sealed class ApprovedTransfer : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U64>
        {
        }
        
        /// <summary>
        /// >> Event: ApprovalCancelled
        /// An approval for account `delegate` was cancelled by `owner`.
        /// \[id, owner, delegate\]
        /// </summary>
        public sealed class ApprovalCancelled : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32>
        {
        }
        
        /// <summary>
        /// >> Event: TransferredApproved
        /// An `amount` was transferred in its entirety from `owner` to `destination` by
        /// the approved `delegate`.
        /// \[id, owner, delegate, destination\]
        /// </summary>
        public sealed class TransferredApproved : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U64>
        {
        }
        
        /// <summary>
        /// >> Event: AssetStatusChanged
        /// An asset has had its attributes changed by the `Force` origin.
        /// \[id\]
        /// </summary>
        public sealed class AssetStatusChanged : BaseTuple<SubstrateNetApi.Model.Types.Primitive.U32>
        {
        }
    }
}
