//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Extrinsics;
using SubstrateNetApi.Model.FrameSupport;
using SubstrateNetApi.Model.Meta;
using SubstrateNetApi.Model.NodeRuntime;
using SubstrateNetApi.Model.PrimitiveTypes;
using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace SubstrateNetApi.Model.PalletProxy
{
    
    
    public sealed class ProxyStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateNetApi.SubstrateClient _client;
        
        public ProxyStorage(SubstrateNetApi.SubstrateClient client)
        {
            this._client = client;
        }
        
        /// <summary>
        /// >> Proxies
        /// </summary>
        public async Task<BaseTuple<SubstrateNetApi.Model.FrameSupport.BoundedVec,SubstrateNetApi.Model.Types.Primitive.U128>> Proxies(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Proxy", "Proxies", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return await _client.GetStorageAsync<BaseTuple<SubstrateNetApi.Model.FrameSupport.BoundedVec,SubstrateNetApi.Model.Types.Primitive.U128>>(parameters, token);
        }
        
        /// <summary>
        /// >> Announcements
        /// </summary>
        public async Task<BaseTuple<SubstrateNetApi.Model.FrameSupport.BoundedVec,SubstrateNetApi.Model.Types.Primitive.U128>> Announcements(SubstrateNetApi.Model.SpCore.AccountId32 key, CancellationToken token)
        {
            var keyParams = new IType[] { key };
            var parameters = RequestGenerator.GetStorage("Proxy", "Announcements", Storage.Type.Map, new[] {Storage.Hasher.Twox64Concat}, keyParams);
            return await _client.GetStorageAsync<BaseTuple<SubstrateNetApi.Model.FrameSupport.BoundedVec,SubstrateNetApi.Model.Types.Primitive.U128>>(parameters, token);
        }
    }
    
    public sealed class ProxyCalls
    {
        
        /// <summary>
        /// >> proxy
        /// </summary>
        public static Method Proxy(SubstrateNetApi.Model.SpCore.AccountId32 real, BaseOpt<SubstrateNetApi.Model.NodeRuntime.EnumProxyType> force_proxy_type, SubstrateNetApi.Model.NodeRuntime.EnumNodeCall call)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(real.Encode());
            byteArray.AddRange(force_proxy_type.Encode());
            byteArray.AddRange(call.Encode());
            return new Method(30, "Proxy", 0, "proxy", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> add_proxy
        /// </summary>
        public static Method AddProxy(SubstrateNetApi.Model.SpCore.AccountId32 @delegate, SubstrateNetApi.Model.NodeRuntime.EnumProxyType proxy_type, SubstrateNetApi.Model.Types.Primitive.U32 delay)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(@delegate.Encode());
            byteArray.AddRange(proxy_type.Encode());
            byteArray.AddRange(delay.Encode());
            return new Method(30, "Proxy", 1, "add_proxy", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> remove_proxy
        /// </summary>
        public static Method RemoveProxy(SubstrateNetApi.Model.SpCore.AccountId32 @delegate, SubstrateNetApi.Model.NodeRuntime.EnumProxyType proxy_type, SubstrateNetApi.Model.Types.Primitive.U32 delay)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(@delegate.Encode());
            byteArray.AddRange(proxy_type.Encode());
            byteArray.AddRange(delay.Encode());
            return new Method(30, "Proxy", 2, "remove_proxy", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> remove_proxies
        /// </summary>
        public static Method RemoveProxies()
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            return new Method(30, "Proxy", 3, "remove_proxies", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> anonymous
        /// </summary>
        public static Method Anonymous(SubstrateNetApi.Model.NodeRuntime.EnumProxyType proxy_type, SubstrateNetApi.Model.Types.Primitive.U32 delay, SubstrateNetApi.Model.Types.Primitive.U16 index)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(proxy_type.Encode());
            byteArray.AddRange(delay.Encode());
            byteArray.AddRange(index.Encode());
            return new Method(30, "Proxy", 4, "anonymous", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> kill_anonymous
        /// </summary>
        public static Method KillAnonymous(SubstrateNetApi.Model.SpCore.AccountId32 spawner, SubstrateNetApi.Model.NodeRuntime.EnumProxyType proxy_type, SubstrateNetApi.Model.Types.Primitive.U16 index, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> height, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> ext_index)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(spawner.Encode());
            byteArray.AddRange(proxy_type.Encode());
            byteArray.AddRange(index.Encode());
            byteArray.AddRange(height.Encode());
            byteArray.AddRange(ext_index.Encode());
            return new Method(30, "Proxy", 5, "kill_anonymous", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> announce
        /// </summary>
        public static Method Announce(SubstrateNetApi.Model.SpCore.AccountId32 real, SubstrateNetApi.Model.PrimitiveTypes.H256 call_hash)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(real.Encode());
            byteArray.AddRange(call_hash.Encode());
            return new Method(30, "Proxy", 6, "announce", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> remove_announcement
        /// </summary>
        public static Method RemoveAnnouncement(SubstrateNetApi.Model.SpCore.AccountId32 real, SubstrateNetApi.Model.PrimitiveTypes.H256 call_hash)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(real.Encode());
            byteArray.AddRange(call_hash.Encode());
            return new Method(30, "Proxy", 7, "remove_announcement", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> reject_announcement
        /// </summary>
        public static Method RejectAnnouncement(SubstrateNetApi.Model.SpCore.AccountId32 @delegate, SubstrateNetApi.Model.PrimitiveTypes.H256 call_hash)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(@delegate.Encode());
            byteArray.AddRange(call_hash.Encode());
            return new Method(30, "Proxy", 8, "reject_announcement", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> proxy_announced
        /// </summary>
        public static Method ProxyAnnounced(SubstrateNetApi.Model.SpCore.AccountId32 @delegate, SubstrateNetApi.Model.SpCore.AccountId32 real, BaseOpt<SubstrateNetApi.Model.NodeRuntime.EnumProxyType> force_proxy_type, SubstrateNetApi.Model.NodeRuntime.EnumNodeCall call)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(@delegate.Encode());
            byteArray.AddRange(real.Encode());
            byteArray.AddRange(force_proxy_type.Encode());
            byteArray.AddRange(call.Encode());
            return new Method(30, "Proxy", 9, "proxy_announced", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> ProxyExecuted
    /// </summary>
    public sealed class EventProxyExecuted : BaseTuple<BaseTuple<BaseTuple,  SubstrateNetApi.Model.SpRuntime.EnumDispatchError>>
    {
    }
    
    /// <summary>
    /// >> AnonymousCreated
    /// </summary>
    public sealed class EventAnonymousCreated : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.NodeRuntime.EnumProxyType, SubstrateNetApi.Model.Types.Primitive.U16>
    {
    }
    
    /// <summary>
    /// >> Announced
    /// </summary>
    public sealed class EventAnnounced : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.PrimitiveTypes.H256>
    {
    }
    
    /// <summary>
    /// >> ProxyAdded
    /// </summary>
    public sealed class EventProxyAdded : BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.NodeRuntime.EnumProxyType, SubstrateNetApi.Model.Types.Primitive.U32>
    {
    }
    
    public enum ProxyErrors
    {
        
        /// <summary>
        /// >> TooMany
        /// </summary>
        TooMany,
        
        /// <summary>
        /// >> NotFound
        /// </summary>
        NotFound,
        
        /// <summary>
        /// >> NotProxy
        /// </summary>
        NotProxy,
        
        /// <summary>
        /// >> Unproxyable
        /// </summary>
        Unproxyable,
        
        /// <summary>
        /// >> Duplicate
        /// </summary>
        Duplicate,
        
        /// <summary>
        /// >> NoPermission
        /// </summary>
        NoPermission,
        
        /// <summary>
        /// >> Unannounced
        /// </summary>
        Unannounced,
        
        /// <summary>
        /// >> NoSelfProxy
        /// </summary>
        NoSelfProxy,
    }
}
