//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletSociety
{
    
    
    public enum BidKind
    {
        
        Deposit,
        
        Vouch,
    }
    
    /// <summary>
    /// >> 437 - Variant[pallet_society.BidKind]
    /// </summary>
    public sealed class EnumBidKind : BaseEnumExt<BidKind, SubstrateNetApi.Model.Types.Primitive.U128, BaseTuple<SubstrateNetApi.Model.SpCore.AccountId32, SubstrateNetApi.Model.Types.Primitive.U128>>
    {
    }
}
