//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletSociety
{
    
    
    /// <summary>
    /// >> 442 - Variant[pallet_society.Error]
    /// Errors for this module.
    /// </summary>
    public enum PalletSocietyError
    {
        
        /// <summary>
        /// >> BadPosition
        /// </summary>
        BadPosition,
        
        /// <summary>
        /// >> NotMember
        /// </summary>
        NotMember,
        
        /// <summary>
        /// >> AlreadyMember
        /// </summary>
        AlreadyMember,
        
        /// <summary>
        /// >> Suspended
        /// </summary>
        Suspended,
        
        /// <summary>
        /// >> NotSuspended
        /// </summary>
        NotSuspended,
        
        /// <summary>
        /// >> NoPayout
        /// </summary>
        NoPayout,
        
        /// <summary>
        /// >> AlreadyFounded
        /// </summary>
        AlreadyFounded,
        
        /// <summary>
        /// >> InsufficientPot
        /// </summary>
        InsufficientPot,
        
        /// <summary>
        /// >> AlreadyVouching
        /// </summary>
        AlreadyVouching,
        
        /// <summary>
        /// >> NotVouching
        /// </summary>
        NotVouching,
        
        /// <summary>
        /// >> Head
        /// </summary>
        Head,
        
        /// <summary>
        /// >> Founder
        /// </summary>
        Founder,
        
        /// <summary>
        /// >> AlreadyBid
        /// </summary>
        AlreadyBid,
        
        /// <summary>
        /// >> AlreadyCandidate
        /// </summary>
        AlreadyCandidate,
        
        /// <summary>
        /// >> NotCandidate
        /// </summary>
        NotCandidate,
        
        /// <summary>
        /// >> MaxMembers
        /// </summary>
        MaxMembers,
        
        /// <summary>
        /// >> NotFounder
        /// </summary>
        NotFounder,
        
        /// <summary>
        /// >> NotHead
        /// </summary>
        NotHead,
    }
}
