//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.SpCore;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletRecovery
{
    
    
    /// <summary>
    /// >> 445 - Composite[pallet_recovery.RecoveryConfig]
    /// </summary>
    public sealed class RecoveryConfig : BaseType
    {
        
        /// <summary>
        /// >> delay_period
        /// </summary>
        private SubstrateNetApi.Model.Types.Primitive.U32 _delayPeriod;
        
        /// <summary>
        /// >> deposit
        /// </summary>
        private SubstrateNetApi.Model.Types.Primitive.U128 _deposit;
        
        /// <summary>
        /// >> friends
        /// </summary>
        private BaseVec<SubstrateNetApi.Model.SpCore.AccountId32> _friends;
        
        /// <summary>
        /// >> threshold
        /// </summary>
        private SubstrateNetApi.Model.Types.Primitive.U16 _threshold;
        
        public SubstrateNetApi.Model.Types.Primitive.U32 DelayPeriod
        {
            get
            {
                return this._delayPeriod;
            }
            set
            {
                this._delayPeriod = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U128 Deposit
        {
            get
            {
                return this._deposit;
            }
            set
            {
                this._deposit = value;
            }
        }
        
        public BaseVec<SubstrateNetApi.Model.SpCore.AccountId32> Friends
        {
            get
            {
                return this._friends;
            }
            set
            {
                this._friends = value;
            }
        }
        
        public SubstrateNetApi.Model.Types.Primitive.U16 Threshold
        {
            get
            {
                return this._threshold;
            }
            set
            {
                this._threshold = value;
            }
        }
        
        public override string TypeName()
        {
            return "RecoveryConfig";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(DelayPeriod.Encode());
            result.AddRange(Deposit.Encode());
            result.AddRange(Friends.Encode());
            result.AddRange(Threshold.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            DelayPeriod = new SubstrateNetApi.Model.Types.Primitive.U32();
            DelayPeriod.Decode(byteArray, ref p);
            Deposit = new SubstrateNetApi.Model.Types.Primitive.U128();
            Deposit.Decode(byteArray, ref p);
            Friends = new BaseVec<SubstrateNetApi.Model.SpCore.AccountId32>();
            Friends.Decode(byteArray, ref p);
            Threshold = new SubstrateNetApi.Model.Types.Primitive.U16();
            Threshold.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
