//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Calls;
using SubstrateNetApi.Model.FrameSupport;
using SubstrateNetApi.Model.PalletUniques;
using SubstrateNetApi.Model.SpRuntime;
using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.PalletUniques
{
    
    
    /// <summary>
    /// >> 301 - Variant[pallet_uniques.pallet.Call]
    /// Contains one variant per dispatchable that can be called by an extrinsic.
    /// </summary>
    public sealed class PalletUniquesCall
    {
        
        /// <summary>
        /// >> create
        /// </summary>
        public GenericExtrinsicCall Create(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress admin)
        {
            return new GenericExtrinsicCall("Uniques", "create", @class, admin);
        }
        
        /// <summary>
        /// >> force_create
        /// </summary>
        public GenericExtrinsicCall ForceCreate(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress owner, SubstrateNetApi.Model.Types.Primitive.Bool free_holding)
        {
            return new GenericExtrinsicCall("Uniques", "force_create", @class, owner, free_holding);
        }
        
        /// <summary>
        /// >> destroy
        /// </summary>
        public GenericExtrinsicCall Destroy(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.PalletUniques.DestroyWitness witness)
        {
            return new GenericExtrinsicCall("Uniques", "destroy", @class, witness);
        }
        
        /// <summary>
        /// >> mint
        /// </summary>
        public GenericExtrinsicCall Mint(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress owner)
        {
            return new GenericExtrinsicCall("Uniques", "mint", @class, instance, owner);
        }
        
        /// <summary>
        /// >> burn
        /// </summary>
        public GenericExtrinsicCall Burn(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance, BaseOpt<SubstrateNetApi.Model.SpRuntime.EnumMultiAddress> check_owner)
        {
            return new GenericExtrinsicCall("Uniques", "burn", @class, instance, check_owner);
        }
        
        /// <summary>
        /// >> transfer
        /// </summary>
        public GenericExtrinsicCall Transfer(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress dest)
        {
            return new GenericExtrinsicCall("Uniques", "transfer", @class, instance, dest);
        }
        
        /// <summary>
        /// >> redeposit
        /// </summary>
        public GenericExtrinsicCall Redeposit(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseVec<SubstrateNetApi.Model.Types.Primitive.U32> instances)
        {
            return new GenericExtrinsicCall("Uniques", "redeposit", @class, instances);
        }
        
        /// <summary>
        /// >> freeze
        /// </summary>
        public GenericExtrinsicCall Freeze(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance)
        {
            return new GenericExtrinsicCall("Uniques", "freeze", @class, instance);
        }
        
        /// <summary>
        /// >> thaw
        /// </summary>
        public GenericExtrinsicCall Thaw(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance)
        {
            return new GenericExtrinsicCall("Uniques", "thaw", @class, instance);
        }
        
        /// <summary>
        /// >> freeze_class
        /// </summary>
        public GenericExtrinsicCall FreezeClass(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class)
        {
            return new GenericExtrinsicCall("Uniques", "freeze_class", @class);
        }
        
        /// <summary>
        /// >> thaw_class
        /// </summary>
        public GenericExtrinsicCall ThawClass(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class)
        {
            return new GenericExtrinsicCall("Uniques", "thaw_class", @class);
        }
        
        /// <summary>
        /// >> transfer_ownership
        /// </summary>
        public GenericExtrinsicCall TransferOwnership(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress owner)
        {
            return new GenericExtrinsicCall("Uniques", "transfer_ownership", @class, owner);
        }
        
        /// <summary>
        /// >> set_team
        /// </summary>
        public GenericExtrinsicCall SetTeam(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress issuer, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress admin, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress freezer)
        {
            return new GenericExtrinsicCall("Uniques", "set_team", @class, issuer, admin, freezer);
        }
        
        /// <summary>
        /// >> approve_transfer
        /// </summary>
        public GenericExtrinsicCall ApproveTransfer(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress @delegate)
        {
            return new GenericExtrinsicCall("Uniques", "approve_transfer", @class, instance, @delegate);
        }
        
        /// <summary>
        /// >> cancel_approval
        /// </summary>
        public GenericExtrinsicCall CancelApproval(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance, BaseOpt<SubstrateNetApi.Model.SpRuntime.EnumMultiAddress> maybe_check_delegate)
        {
            return new GenericExtrinsicCall("Uniques", "cancel_approval", @class, instance, maybe_check_delegate);
        }
        
        /// <summary>
        /// >> force_asset_status
        /// </summary>
        public GenericExtrinsicCall ForceAssetStatus(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress owner, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress issuer, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress admin, SubstrateNetApi.Model.SpRuntime.EnumMultiAddress freezer, SubstrateNetApi.Model.Types.Primitive.Bool free_holding, SubstrateNetApi.Model.Types.Primitive.Bool is_frozen)
        {
            return new GenericExtrinsicCall("Uniques", "force_asset_status", @class, owner, issuer, admin, freezer, free_holding, is_frozen);
        }
        
        /// <summary>
        /// >> set_attribute
        /// </summary>
        public GenericExtrinsicCall SetAttribute(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseOpt<SubstrateNetApi.Model.Types.Primitive.U32> maybe_instance, SubstrateNetApi.Model.FrameSupport.BoundedVec key, SubstrateNetApi.Model.FrameSupport.BoundedVec value)
        {
            return new GenericExtrinsicCall("Uniques", "set_attribute", @class, maybe_instance, key, value);
        }
        
        /// <summary>
        /// >> clear_attribute
        /// </summary>
        public GenericExtrinsicCall ClearAttribute(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseOpt<SubstrateNetApi.Model.Types.Primitive.U32> maybe_instance, SubstrateNetApi.Model.FrameSupport.BoundedVec key)
        {
            return new GenericExtrinsicCall("Uniques", "clear_attribute", @class, maybe_instance, key);
        }
        
        /// <summary>
        /// >> set_metadata
        /// </summary>
        public GenericExtrinsicCall SetMetadata(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance, SubstrateNetApi.Model.FrameSupport.BoundedVec data, SubstrateNetApi.Model.Types.Primitive.Bool is_frozen)
        {
            return new GenericExtrinsicCall("Uniques", "set_metadata", @class, instance, data, is_frozen);
        }
        
        /// <summary>
        /// >> clear_metadata
        /// </summary>
        public GenericExtrinsicCall ClearMetadata(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> instance)
        {
            return new GenericExtrinsicCall("Uniques", "clear_metadata", @class, instance);
        }
        
        /// <summary>
        /// >> set_class_metadata
        /// </summary>
        public GenericExtrinsicCall SetClassMetadata(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class, SubstrateNetApi.Model.FrameSupport.BoundedVec data, SubstrateNetApi.Model.Types.Primitive.Bool is_frozen)
        {
            return new GenericExtrinsicCall("Uniques", "set_class_metadata", @class, data, is_frozen);
        }
        
        /// <summary>
        /// >> clear_class_metadata
        /// </summary>
        public GenericExtrinsicCall ClearClassMetadata(BaseCom<SubstrateNetApi.Model.Types.Primitive.U32> @class)
        {
            return new GenericExtrinsicCall("Uniques", "clear_class_metadata", @class);
        }
    }
}
