//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.SpArithmetic
{
    
    
    /// <summary>
    /// >> 299 - Composite[sp_arithmetic.per_things.Perquintill]
    /// </summary>
    public sealed class Perquintill : BaseType
    {
        
        /// <summary>
        /// >> value
        /// </summary>
        private SubstrateNetApi.Model.Types.Primitive.U64 _value;
        
        public SubstrateNetApi.Model.Types.Primitive.U64 Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        
        public override string TypeName()
        {
            return "Perquintill";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Value.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Value = new SubstrateNetApi.Model.Types.Primitive.U64();
            Value.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
